### ISSUE TITLE
No Anti-aliasing on lines from indexedLineSet

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#104]
A minor thing, but I noticed that lines from an indexedLineset look a bit rough in X_ITE
There is no anti-aliasing.
 
![ils_bs_contact](https://user-images.githubusercontent.com/6066508/158057350-bfa56097-4826-410f-a821-163a59b90124.png)
With BS Contact

![ils_x_ite](https://user-images.githubusercontent.com/6066508/158057351-b09a62f6-a28b-481c-85ae-ab719439f006.png)
With X_ITE

I am not sure if there is a setting I missed.
Other shapes look great and the movement between viewpoints is much smoother in X_ITE.

Windows 10
Google Chrome: Version 99.0.4844.51 (Official Build) (64-bit)
X_ITE: v4.7.15

**Comment by create3000** [comment]
The lines in your image should be antialiased, but depending on the antialiasing setting of the browser, the images can differ. You can check if antialiasing is enabled in X_ITE if you check the Wellcome-Message in the console. There should be something like this to read:

```
Rendering Properties
      Antialiased: true
```

I do not explicitly set antialiasing option when the WebGL context is create, but by NOT setting the flag the browser will generally try to use antialiasing.

**Comment by olafgithub** [comment]
I checked the AA setting in X_ITE. It is (and was) **On** all the time.

I did not mention that with BS_Contact I use Direct X and not OpenGL as renderer.
When I changed the renderer in BS_Contact to OpenGL the results are about the same as X_ITE.
There is also a setting in BS_Contact under **Graphics -> Edges -> Antialias** 
When I check this option I see another problem: Lines close to the viewer are rendered too wide...

Just to be sure why the lines look smoother in BS_Bontact using DirectX I did a comparison:

![reference](https://user-images.githubusercontent.com/6066508/158154050-556d0de9-34a0-4aaa-8708-c3723ff16289.png)

Part of a scene

![bs_contact_direct_x_1000pct](https://user-images.githubusercontent.com/6066508/158154139-e65da04c-ad3a-40f9-aa93-86ac68bf2a19.png)

At 1000% as rendered in BS_Contact with DirectX

![x_ite_1000pct](https://user-images.githubusercontent.com/6066508/158154273-e945cba0-064e-454a-ae9a-0bcc2a1eb88a.png)

At 1000% as rendered in X_ITE (with antialias On)

Looks very different...

All this may seem not very important, but I used IndexedLineSet to make a 3D wiring diagram of a motorcycle. When you hover the mouse over a wire, the details are displayed on a Billboard node.

The other bug (No TouchSensor on IndexedLineSet) is of course much more important.

Thanks for looking into this,

Olaf

**Comment by create3000** [comment]
The images of you show that the lines are antialiased. When one set the antialiasing in OpenGL there is a 'strength' value, which can be 0,2,4,8,16,32. Probabl BS Contact has a higher antialiasing strength. When no antialiasing would be applied you would see every pixel of the line with the same color as shown below.

![tmp10a0143_thumb](https://user-images.githubusercontent.com/2930196/158214867-5555e8d6-32a5-4c4b-a135-04c794692f0b.png)

**Comment by olafgithub** [comment]
Correct.

I assumed that there was no antialiasing at all. Only when I took a screenshot did I see that there is indeed some antialiasing.
At first, it looked like a simple Bresenham's line to me.

The nicest lines are seen when BS Contact is rendering with DirectX.

Thanks for looking into it.

Olaf
