### ISSUE TITLE
The copy viewpoint with Shift-F8 BUG is back again

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#105]
**Describe the bug**
When I view a scene with a number of viewpoints and use Home, Page-Up, or Page-Down to select a viewpoint and then move to a different viewpoint by zooming, moving dragging etc. and then use Shift-F8 to copy the **current** **viewpoint** to the clipboard **I get the last viewpoint** (from the preset viewpoints) I visited.

**To Reproduce**
Navigate to a preset viewpoint using Page-Down
Move viewpoint a bit with dragging zooming etc
Use Shift-F8 to cop
Observe that the viewpoint (also on the console) is the same as the last preset viewpoint **visited**

**Desktop (please complete the following information):**
Windows 10
Google Chrome Version 99.0.4844.51 (Official Build) (64-bit)

**NOTE**

When I remove all viewpoints and then create a few while moving around in the scene it works fine: proper viewpoints are copied.

**When I add the description field and fill in a description** and reload the scene every Shift-F8 copy results in the latest viewpoint I visited using the menu or Page-Up or Page-Down.

Olaf

**Comment by create3000** [comment]
Have now released version 5.0.0.
