### ISSUE TITLE
background

### ISSUE THREAD

**Issue by binoclard2005** [create3000/x_ite#107]
**Describe the bug**

Background {
	skyColor [0 0 1,.9 .9 1]
	skyAngle 4.5
}

**To Reproduce**
in blaxxun contact :  
![image](https://user-images.githubusercontent.com/79451050/160293875-3e564342-aeed-4c66-95a2-fe105386477b.png)
in x_ite : 
![image](https://user-images.githubusercontent.com/79451050/160293908-9d6b7d42-03e8-4399-92f8-4a27fcfb2a76.png)

**Desktop (please complete the following information):**

- w10
- chrome 
- x_ite

how make a sky ?
Thank :)
Marco

**Comment by create3000** [comment]
If you only use skyColor/Angle, skyAngle can only be maximum PI (half circle). Your value 4.5 is far away of that. If you use sky and ground the angles can only be PI/2 (quarter circle). A complete reference for Background node can be found here: https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/environmentalEffects.html#Backgrounds.

**Comment by create3000** [comment]
Sometimes an image says more than thousand words, here is an example background to study:

```js
DEF Summer Background {
  skyAngle [
    0.8,
    1.3,
    1.4,
    1.5708
  ]
  skyColor [
    0.21 0.31 0.59,
    0.33 0.45 0.7,
    0.57 0.66 0.85,
    0.6 0.73 0.89,
    0.7 0.83 0.98
  ]
  groundAngle [
    0.659972,
    1.2,
    1.39912,
    1.5708
  ]
  groundColor [
    0.105712 0.156051 0.297,
    0.187629 0.255857 0.398,
    0.33604 0.405546 0.542,
    0.3612 0.469145 0.602,
    0.39471 0.522059 0.669
  ]
}
```

<img width="833" alt="Bildschirmfoto 2022-03-29 um 09 33 05" src="https://user-images.githubusercontent.com/2930196/160558295-f6e1f3c8-b340-45a4-a4b8-a4e2e849bec2.png">

**Comment by binoclard2005** [comment]
ok i use your code but , he is not working ;(

**Comment by binoclard2005** [comment]
![image](https://user-images.githubusercontent.com/79451050/160606106-56a08fb2-4b18-43fb-8441-5a1a585e53ea.png)

**Comment by binoclard2005** [comment]
this is good ?

**Comment by create3000** [comment]
I have tested it and It looks good. Another example of a scene with Background can be found here https://create3000.github.io/media/examples/EnvironmentalEffects/Background/example.html.

**Comment by binoclard2005** [comment]
tomorow i test this code :p

**Comment by create3000** [comment]
Your Background is in an Inline node, and therefore not bound. You have to bind it per Script, or VisibilitySensor, or ProximitySensor, or you put the Background directly in the file you load.

**Comment by create3000** [comment]
You can directly load every file by using the `src` attribute, then your Viewpoint, Background, NavigationInfo specified in `test_monde.wrl `will be bound on load:

```html
<X3DCanvas src="http://starenda.info/test_monde.wrl"></X3DCanvas>
```
