### ISSUE TITLE
use a gif or png ?

### ISSUE THREAD

**Issue by binoclard2005** [create3000/x_ite#108]
**Describe the bug**
i want use a gif animated

**To Reproduce**
with gif animated in ITE
![image](https://user-images.githubusercontent.com/79451050/160770017-8cafcb40-07f3-4e21-8656-c402fac887fe.png)
![image](https://user-images.githubusercontent.com/79451050/160770479-31da5547-df53-4cf5-be7a-64e40825b6bf.png)

 in blaxxun contact and cortona
![image](https://user-images.githubusercontent.com/79451050/160770145-49d69c1c-589d-443a-aee3-30b9dc41dda6.png)
![image](https://user-images.githubusercontent.com/79451050/160770192-befebc51-299b-4de9-8dfe-3fe8ee271196.png)

it is normal ?
thank

**Comment by create3000** [comment]
You can use png, jpg, gif, or svg. All images your browser supports. I have looked at your site, opened the **_Developer Console,_** and found out that various images are not loaded, probably because the file path is not correct. You also can open the **_Developer Console_** to check if there are some errors.

**Comment by binoclard2005** [comment]
ho< to call develloper console ?

**Comment by create3000** [comment]
Website and documentation for X_ITE is here https://create3000.github.io/x_ite/.

Developer console:  https://www.google.com/search?client=safari&rls=en&q=edge+open+developer+console&ie=UTF-8&oe=UTF-8

**Comment by binoclard2005** [comment]
it is only console of chrome ?
ok, i know :)

**Comment by binoclard2005** [comment]
https://www.b-ecard.net/x_ite3d/doku.php

if you want write a full documentation here 👍 
https://www.b-ecard.net/x_ite3d/doku.php
