### ISSUE TITLE
Only 4 lights supported in a world

### ISSUE THREAD

**Issue by smile0711** [create3000/x_ite#112]
**Describe the bug**
After adding my 5th light node, it seems as if x_ite ignores any light nodes after the 4th one.

**To Reproduce**
1. add more than 4 light nodes to a .wrl

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux, windows, mac
 - Browser chrome, edge, safari
 - unknown

**Additional context**
All of my users are complaining about a wrl not being lit properly.
This is not tied to the new update as we are using an older version

**Comment by create3000** [comment]
The number of simultaneous global lights are limited by your hardware and graphics card driver. You can check how much lights are supported by opening your browsers developer console, and read X_ITE's welcome message. 

To have more lights you can use local lights as much as you want, with the exception that there can only as much local lights in a group as the number of global lights is (on your system 4).

To create a local light set the _global_ field of your light node to `FALSE`.

**Comment by create3000** [comment]
Are you OK with this?

**Comment by smile0711** [comment]
So to clarify for me.  If I have 4 global lights then I can also have up to 16 local lights.  OR if my computer only supports 4 then I can I have 4 more local

**Comment by create3000** [comment]
If you have 4 global lights you can have 4 local lights per Shape node, you can also mix global and local light, for instance you could have 1 global DirectionalLight and 3 local SpotLights for a Shape node. The following code would be legal for you:

```js
DirectionalLight { global TRUE }
Transform {
  DEF L1 SpotLight { global FALSE }
  DEF L2 SpotLight { global FALSE }
  DEF L3 SpotLight { global FALSE }
  Shape { ... }
}
Transform {
  DEF M1 SpotLight { global FALSE }
  DEF M2 SpotLight { global FALSE }
  DEF M3 SpotLight { global FALSE }
  Shape { ... }
}
```

**Comment by smile0711** [comment]
Perfect.  Thanks!

**Comment by Sgeo** [comment]
I'm trying to understand the lighting limitation.

It seems to be tied to `MAX_TEXTURE_IMAGE_UNITS`.

Am I correct in understanding that the only place that uses texture units in a quantity related to number of lights is shadows?

Would it be possible to have more lights if shadows are turned off?

**Comment by create3000** [comment]
Light are limited to 8 lights per Shape, because lighting is very expensive. This 8 lights can be either global or local. If shadows are turned on, yes, it depends also on `MAX_TEXTURE_IMAGE_UNITS`.

**Comment by create3000** [comment]
Is it possible that you describe what you are trying to achieve?

**Comment by create3000** [comment]
As I mentioned before, 8 lights are now possible. So this should be possible, at least without shadows. If you turn on shadows, I would recommend to do this only with one lights and in in a limited area.

There is also a new field in Inline node called `global`. When set to `false`, all lights in the Inline node become local to the Inline node. This field is standardized and new to X3D4.0. See https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/components/networking.html#Inline.
