### ISSUE TITLE
Default field values not copied from script in external PROTO

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#115]
When rewriting some code for X_ITE I got a division-by-zero error.
After some investigation, I found out that maybe there is a bug related to default fields in the script node that is defined as an external proto.

What I did was:

Define a proto of a script node (ExtScript)  in file "bug_ext.wrl"
The script has a field value: **field     SFFloat   span      123**

When I use the proto ExtScript in file "bug_main.wrl" the field span is reported as 123 (Correct).
When I use the proto ExtScript in another proto in file "bug_main.wrl" the value is 0 (zero).

Code in the proto ExtScript print the value of span on the console during **init** and when running a function.
The test world is a yellow sphere with a plane sensor.
When you move the sphere the script is called.
The script reports the value of span as zero (the bug).

**code in bug_ext.wrl:**

```js
#VRML V2.0 utf8

PROTO ExtScript
[
  field     SFFloat   span      123

  eventIn   SFVec3f   pos_in
]
{
  Script
  {
    eventIn   SFVec3f   pos_in  IS  pos_in
    field     SFFloat   span    IS  span

    url "javascript:
   
      function initialize()
      {
        print( 'function initialize()::span: ' + span );
      }

      function pos_in ( p )
      {
        print( 'function pos_in( '+ p + ' ) span: ' + span );
      }
    "
  }    
}
```

**code in bug_main.wrl:**

```js
#VRML V2.0 utf8                 


EXTERNPROTO ExtScript
[
  field     SFFloat   span

  eventIn   SFVec3f   pos_in
]
[
  "./bug_ext.wrl#ExtScript"
]


PROTO Cursor []
{
  Group
  {
    children
    [
      DEF SCR ExtScript {}

      DEF TR Transform 
      {
        children
        [
          Group
          {
            children
            [
              Shape
              {
                appearance Appearance { material Material { diffuseColor 1 1 0 } }
                geometry Sphere { radius 20 }
              }
              
              DEF PS PlaneSensor
              {
                minPosition  -100  0
                maxPosition   100  0
              }
            ]
          }
        ]
      } 
    ]
    ROUTE PS.translation_changed  TO  TR.translation
    ROUTE PS.translation_changed  TO  SCR.pos_in
  }
}


ExtScript {}      # works ok: default is copied
Cursor {}         # bug 

Viewpoint 
{
  position     4.039 12.989 366.290
  orientation  0.000 0.000 1.000 0.000
  fieldOfView  0.716
}
```

Windows 10
Google Chome
X_ITE: v5.0.3

**Comment by create3000** [comment]
Fixed this and released new version 5.0.4.

**Comment by olafgithub** [comment]
Great!
I just tested it and indeed it works. So this was a real bug after all?

Olaf

**Comment by create3000** [comment]
Yes there was a bug in initialization of proto instances.

**Comment by create3000** [comment]
Closed, because it is fixed.
