### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by anonimo82** [create3000/x_ite#116]
Hello everyone.
I'd like to suggest to add markup needed to have intellisense working in IDEs.
I guess that's type annotations, but I'm not sure.

Thanks for any help, and please, let me know if it's indeed type annotations.

**Comment by create3000** [comment]
I know that the code of X_ITE is rarely documented and coding help in IDEs like Visual Studio Code do not work. But we keep this in mind.

In the meanwhile you can use the online reference where all public functions, properties, and types are documented.

https://create3000.github.io/x_ite/
https://create3000.github.io/x_ite/reference/ECMAScript-Object-and-Function-Definitions.html
https://create3000.github.io/x_ite/Accessing-the-External-Browser.html

**Comment by create3000** [comment]
X_ITE uses now native JavaScript import system, and WebPack to package. Maybe intellisense is working better now.

**Comment by create3000** [comment]
I think we are now on the way. See https://github.com/create3000/x_ite/issues/152
