### ISSUE TITLE
loading time is too long

### ISSUE THREAD

**Issue by YUE-8152** [create3000/x_ite#118]
**Describe the bug**
The file size exceeds 100M, and loading takes a long time. How can I reduce the loading time?

**Comment by create3000** [comment]
100MB are indeed very much. But there are a few thing you could do:

* Use cloned nodes to reduce file size.
* Use optimized geometry nodes like IndexedTriangleSet or TriangleSet in favor of IndexedFaceSet.
* Configure your web server to serve Gzipped files, this would reduce download time.

See also:
* https://create3000.github.io/x_ite/How-To-Configure-Your-Web-Server.html
* https://create3000.github.io/x_ite/tutorials/Improving-Performance.html

**Comment by create3000** [comment]
If there is no communication in the next week on this channel, I will close this issue.

**Comment by create3000** [comment]
With the new release of today (v8.8.0), the X_ITE VRML and XML parsers are now up to 40% faster in parsing large models with lots of points, colors and normals.

If you have the chance, please give it a try.
