### ISSUE TITLE
How does x3d Canvas display toolbars to control views?

### ISSUE THREAD

**Issue by yeehome** [create3000/x_ite#119]
How does x3d Canvas display toolbars to control views?

**Comment by create3000** [comment]
There are no toolbars includes in a &lt;x3d-canvas&gt; element. Only a context menu is available. If you want a toolbar you can build it by your own with HTML, CSS, and JavaScript. There is a Browser element and several options which can be adjusted with JavaScript.

See also:

* https://create3000.github.io/x_ite/Accessing-the-External-Browser.html
* https://create3000.github.io/x_ite/reference/ECMAScript-Object-and-Function-Definitions.html

**Comment by yeehome** [comment]
Thank you very much！
