### ISSUE TITLE
site using tested version stopped working

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#120]
(some time in last few weeks)

> Loading failed for the <script> with source “https://create3000.github.io/code/x_ite/5.0.4/dist/x_ite.min.js”.

'latest' OK other versions not found

**Comment by create3000** [comment]
Unfortunately I cannot continue host versions of x_ite on GitHub. But versions are still available via jsdelivr.

```html
<script src="https://cdn.jsdelivr.net/gh/create3000/x_ite@8.0.0/dist/x_ite.min.js"></script>
```

Replace 8.0.0 with the version you prefer.

See also https://create3000.github.io/x_ite/#for-production.
