### ISSUE TITLE
XML Parser Error: Unknown node type 'TEXT', you probably have insufficient component/profile statements.

### ISSUE THREAD

**Issue by jamesleesaunders** [create3000/x_ite#125]
**Describe the bug**
Seeing new console error in v8.3.0:
```
XML Parser Error: Unknown node type 'TEXT', you probably have insufficient component/profile statements.
```

This error is not seen on version prior to v8.3.0.
I assume this is complaining about the following text elements used on the axis:

```
<billboard axisofrotation="0 0 0">
   <shape>
      <appearance>
         <material diffusecolor="0.0000 0.0000 0.0000"></material>
      </appearance>
      <text string="&quot;1&quot;">
         <fontstyle size="1.3" family="&quot;SANS&quot;" style="BOLD" justify="&quot;MIDDLE&quot; &quot;MIDDLE&quot;"></fontstyle>
      </text>
   </shape>
</billboard>
```

**To Reproduce**
Goto: https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X_ITE/chart/SpotPlot.html
Open JS Console.

**Environment:**
Welcome to X_ITE X3D Browser v8.3.0:
   Current Graphics Renderer
      Name: Google Inc. (Apple) ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
      WebGL version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
      Shading language: WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)

Chrome 
OSX

**Comment by jamesleesaunders** [comment]
Ahh, this is only an issue when I have profile=Interactive. If I go to Full it does not error about TEXT node type.
Should this happen?
(I switches to Interactive to stop the Tesxture3d.js asm warnings)

**Comment by create3000** [comment]
Because it is now possible and because the Text component is a littler larger I made an external component of it and it is only loaded on demand now. 

This means for you the Interactive profile does not include the Text component and therefor you should add it manually if needed. X3D nodes are grouped in components and components are grouped in profiles. To add a component to your X3D world use the following example code.

```xml
<X3D profile='Interactive' version='4.0'>
  <head>
    <component name='Text' level='1'/>
  </head>
...
```

https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/Architecture.html

**Comment by create3000** [comment]
I now could get rid of the Texture3D.js asm warnings. But I really want to encourage you to use the right component/profile statements.

**Comment by jamesleesaunders** [comment]
Brill Thanks again!
I have added head + component = Text and this appears to be all good. 😄 

I see now from the Interactive profile that Text is not listed in the Components and levels section:
https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/interactive.html
So I now understand why you removed it.

Sorry I have raised a few bugs recently - It feels like I am turning into your #1 tester!  .. I have learn lots along the way also!

I have also make sure adding this head + component works with x3dom as I am keen to keep d3-x3d agnostic and work on both x3dom and x_ite).

**Comment by create3000** [comment]
Don't bother to submit bug reports. Every issue is welcome. 

Component/profile statement are integral part of X3D and therefor well specified.

Have a look at the Web3D.org examples archive, all examples have component/profile statements, and can be tests either in X3DOM or in X_ITE.

https://www.web3d.org/x3d/content/examples/Basic/

**Comment by andreasplesch** [comment]
> Brill Thanks again! I have added head + component = Text and this appears to be all good. smile
> 
> I see now from the Interactive profile that Text is not listed in the Components and levels section: https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/interactive.html So I now understand why you removed it.
> 
> Sorry I have raised a few bugs recently - It feels like I am turning into your #1 tester! .. I have learn lots along the way also!
> 
> I have also make sure adding this head + component works with x3dom as I am keen to keep d3-x3d agnostic and work on both x3dom and x_ite).

x3dom ignores profiles and component statements to keep things simple and avoid traffic.
