### ISSUE TITLE
Playground color scheme hard to read

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#128]
The ace color scheme with dark blue tags on dark grey background is very hard to read.

https://create3000.github.io/x_ite/playground/

**Comment by create3000** [comment]
I assume you have light theme enabled for the website. Have only tested for dark, will probably remove the possibility to changed theme.

**Comment by andreasplesch** [comment]
The light theme seems to be the default since I had not discovered that there is an option for a dark theme. With the dark theme it looks great.

**Comment by create3000** [comment]
Should be fixed now.
