### ISSUE TITLE
Assignment to a constant (trackPoint)

### ISSUE THREAD

**Issue by emilis-ideait** [create3000/x_ite#134]
There is assignment to a constant in code:

https://github.com/create3000/x_ite/blob/0bca59b6e774e3b68a849424c6a37c0e2475423c/src/x_ite/Components/PointingDeviceSensor/PlaneSensor.js#L199

It prevented me from importing X_ITE in my project.

**Comment by create3000** [comment]
Released version 8.6.17, which fixes the issue. Please have another try.

**Comment by emilis-ideait** [comment]
Thank you! Importing works now.
