### ISSUE TITLE
Use optional url parameter for playground

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#135]
https://create3000.github.io/x_ite/playground/?uri=https://myserver/myX3d.x3d

would then load the x3d from the link into the editor. This could be useful for sharing simple x3d files.

It may be not too much work to do. I may be able to give it a try.

**Comment by andreasplesch** [comment]
Something like this in [playground.html](https://github.com/create3000/x_ite/blob/89cb67db448ebe9639523b1e1336a06ed2d3140f/docs/_tabs/playground.html#L158)
```js
const url = new URL (document .location .href) .searchParams .get ("url");
if (url .endsWith (".x3d")) {
        fetch (url)
        .then ( (r) => r .ok ? r .text () : "Response was not ok trying to fetch url: " + url)
        .then ( (t) => editor .setValue (t))
        .catch ( () => editor .setValue ("failed loading"));
}
else {editor . setValue (box .replace(/ {3}/g, "  "));}
```
seems to work well enough.

**Comment by andreasplesch** [comment]
Thanks. Works great:

https://create3000.github.io/x_ite/playground/?url=https://gist.githubusercontent.com/andreasplesch/dc3595c5cf5198bedd7dbdb119a7a059/raw/4c9aed0dd47191873fc4e87870125eecc75c1ab1/jscad.x3d

**Comment by andreasplesch** [comment]
This works as well:

https://create3000.github.io/x_ite/playground/?url=https://corsproxy.io/?https://www.web3d.org/x3d/content/examples/ConformanceNist/Geometry/IndexedLineSet/coordIndex_colorCanonical.xml

**Comment by andreasplesch** [comment]
Thanks. It turns out that there was a problem [with data urls](https://create3000.github.io/x_ite/playground/?url=data:text/plain;base64,PFgzRD4KICA8U2NlbmU+CiAgICA8U2hhcGU+CiAgICAgIDxBcHBlYXJhbmNlIERFRj0nYTAnPgogICAgICAgIDxNYXRlcmlhbCBkaWZmdXNlQ29sb3I9JzAuMSAwLjEgMC4xJyBzcGVjdWxhckNvbG9yPScwLjA1IDAuMDUgMC4wNScvPgogICAgICA8L0FwcGVhcmFuY2U+CiAgICAgIDxDeWxpbmRlciBoZWlnaHQ9JzE2JyByYWRpdXM9JzIuNScgc3ViZGl2aXNpb249JzgnLz4KICAgIDwvU2hhcGU+CiAgICA8VHJhbnNmb3JtIHRyYW5zbGF0aW9uPScwIDggLTInPgogICAgICA8U2hhcGU+CiAgICAgICAgPEFwcGVhcmFuY2UgVVNFPSdhMCcvPgogICAgICAgIDxFeHRydXNpb24gCiAgICAgICAgIGNyb3NzU2VjdGlvbj0nLTAuMjUgLTIsIC0wLjUgMCwgLTAuMjUgMiwgMC4yNSAyLCAwLjUgMCwgMC4yNSAtMiwgLTAuMjUgLTInCiAgICAgICAgIHNwaW5lPScwIDAgMCwgLTMuNSAwIDEuNSwgLTUgMCA1LCAtMy41IDAgOC41LCAwIDAgMTAsIDMuNSAwIDguNSwgNSAwIDUsIDMuNSAwIDEuNSwgMCAwIDAnPgogICAgICAgIDwvRXh0cnVzaW9uPgogICAgICA8L1NoYXBlPgogICAgPC9UcmFuc2Zvcm0+CiAgPC9TY2VuZT4KPC9YM0Q+) .

I finally discovered that the searchParams property does not work with data urls. It destroys some characters, probably trying to find multiple parameters.

Here is a simple regex match instead which worked well:

```js
const url = new URL(document.location.href).search.match(/^\?url=(.*)/);

if (url) {
    try {
        const response = await fetch(url[1]) //first capture group
          , text = response.ok ? await response.text() : "Response was not ok trying to fetch url: " + url[1];

        editor.setValue(text);
    } catch (error) {
        editor.setValue(error.message);
    }
} else {
    editor.setValue(box.replace(/ {3}/g, "  "));
}
```

**Comment by create3000** [comment]
Yes, parts of search param must be encoded with `encodeURIComponent` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), and thus later be decoded with `decodeURIComponent`.

**Comment by create3000** [comment]
This means, I would rather do:

```js
const url = decodeURIComponent (new URL (document .location .href) .searchParams .get ("url"));
...
```

**Comment by andreasplesch** [comment]
I tried that, it did not work, unfortunately.

**Comment by andreasplesch** [comment]
```js
const url = new URL(document.location.href);

if (url.searchParams.get("url")) {

  const dummyURL = new URL( 'http://dummy/' + encodeURIComponent (url.search.slice ( 5 ) )); //?url= exists but may not be first
  const realUrl = decodeURIComponent ( dummyURL.pathname.slice ( 1 ));
...
```
seems to work but it may be messier than the regex?

**Comment by create3000** [comment]
If I encode `data:model/x3d+xml,<Shape><Text string='"Hello: ?&amp;"'/></Shape>` and then create the link https://create3000.github.io/x_ite/playground/?url=data%3Amodel%2Fx3d%2Bxml%2C%3CShape%3E%3CText%20string%3D%27%22Hello%3A%20%3F%26amp;%22%27%2F%3E%3C%2FShape%3E, which will work.

**Comment by andreasplesch** [comment]
ok,[ percentencoded dataurls](https://create3000.github.io/x_ite/playground/?url=data:text/plain;base64,PFgzRD4KICA8U2NlbmU%2BCiAgICA8U2hhcGU%2BCiAgICAgIDxBcHBlYXJhbmNlIERFRj0nYTAnPgogICAgICAgIDxNYXRlcmlhbCBkaWZmdXNlQ29sb3I9JzAuMSAwLjEgMC4xJyBzcGVjdWxhckNvbG9yPScwLjA1IDAuMDUgMC4wNScvPgogICAgICA8L0FwcGVhcmFuY2U%2BCiAgICAgIDxDeWxpbmRlciBoZWlnaHQ9JzE2JyByYWRpdXM9JzIuNScgc3ViZGl2aXNpb249JzgnLz4KICAgIDwvU2hhcGU%2BCiAgICA8VHJhbnNmb3JtIHRyYW5zbGF0aW9uPScwIDggLTInPgogICAgICA8U2hhcGU%2BCiAgICAgICAgPEFwcGVhcmFuY2UgVVNFPSdhMCcvPgogICAgICAgIDxFeHRydXNpb24gCiAgICAgICAgIGNyb3NzU2VjdGlvbj0nLTAuMjUgLTIsIC0wLjUgMCwgLTAuMjUgMiwgMC4yNSAyLCAwLjUgMCwgMC4yNSAtMiwgLTAuMjUgLTInCiAgICAgICAgIHNwaW5lPScwIDAgMCwgLTMuNSAwIDEuNSwgLTUgMCA1LCAtMy41IDAgOC41LCAwIDAgMTAsIDMuNSAwIDguNSwgNSAwIDUsIDMuNSAwIDEuNSwgMCAwIDAnPgogICAgICAgIDwvRXh0cnVzaW9uPgogICAgICA8L1NoYXBlPgogICAgPC9UcmFuc2Zvcm0%2BCiAgPC9TY2VuZT4KPC9YM0Q%2B), will work, and are probably ok to expect.

(This is almost black)

**Comment by create3000** [comment]
Files loaded with url parameter, do now support relative URL's inside, even if they are edited later. :)

**Comment by andreasplesch** [comment]
Very nice !
