### ISSUE TITLE
Doubts at rendering the X3D component in DOM

### ISSUE THREAD

**Issue by GuilhermeLuanMorais** [create3000/x_ite#139]
Hi,
I am trying to renderize the X3D in the DOM, but by passing the byte array to the src of <x3d-canvas>, the byte array is a WRL file, that is an attribute from an object that I am returning from my java controller.
at my case, the 3D is not rendering properly.
There is a way to render the byte array or base64 String in DOM without using the @Produces((VRML_CONTENT}) ?

**Comment by create3000** [comment]
You could do:

```html
<x3d-canvas src="data:model/vrml;base64,..."></x3d-canvas>
```

additionally you can set the `baseURL` attribute, where you can specify a URL against which relative urls are resolved.

**Comment by GuilhermeLuanMorais** [comment]
Perfect, I will try this, than you for answering me.

**Comment by GuilhermeLuanMorais** [comment]
Why this is happening ?
![image](https://github.com/create3000/x_ite/assets/10600518/182c908c-7e5e-416a-8b92-8fc671fc165c)

When I execute this line i get this error:
![image](https://github.com/create3000/x_ite/assets/10600518/83440e01-8940-4a62-acf7-b16600757f5a)

The response[1].fileBase64 is in this format: data:model/vrml;base64,...
Can it be my string64 ?

**Comment by create3000** [comment]
Could you please provide the file causing the error?

**Comment by GuilhermeLuanMorais** [comment]
I make it work in my project with my base64 like you said. Its working perfect, but now I am trying to check why this is happening.

![image](https://github.com/create3000/x_ite/assets/10600518/bf900a80-f7fc-43e0-aac1-6590b91bfc86)

Its a big page with a lot of libs, I'm trying to find which is causing conflict with your lib.

**Comment by create3000** [comment]
From my side of view this error should not happen at all. The error happens when `refineNormals` is called from IndexedFaceSet, but it is really impossible that this error can happen, the code is very save. 

Second it happens when the default Sphere node geometry is created, what is extensively tested.

**Comment by create3000** [comment]
Why do you get a 404 error that the CSS could not be loaded?

> GET https://local.weg.net:9002/catalog/ui/desktop/common/js/xite-8.9.2/x_ite.css net::ERR_ABORTED 404

**Comment by create3000** [comment]
After some investigation, I figured out that the error can happen if someone in you code does `Array.prototype.foo=1` or something like that. (Don't do this.)

I have changed X_ITE, so it will not be affected by that, and released a new version. Please give version 8.9.3 a try.

**Comment by GuilhermeLuanMorais** [comment]
Good morning, 
Yes, it was not loading the css in the moment that I took the printscreen, but after I have included and got the same error.

Thanks for the answer. I will try again and get back to report the status with more details.

**Comment by GuilhermeLuanMorais** [comment]
I can confirm that this is a bug, because I put x3d-canvas in a simple page from my project an it worked, with rotation by cursor. 
What is happening in my "complete page with a lot of libs" is that when I hold the click to rotate the object, it moves all the element.

**Comment by create3000** [comment]
Thank you for your patience and identifying this bug. 

CSS transforms are now handled correctly. Fixed version is 8.9.6.
