### ISSUE TITLE
Sound stereo direction in VRML

### ISSUE THREAD

**Issue by vralexllobet** [create3000/x_ite#145]
Hi All, I have a 3D site written in VRML.  The sound is not moving across stereo speakers as I rotate away from the sound left or right.  
You can see my example on my site https://vr.alexllobet.com/wtc/wtc.html

In Firefox I hear the fountain sound but it doesn't move around the stereo image left/right.
Thanks for such great code that enabled me to finally put up my 3D VRML site up again!

**Comment by create3000** [comment]
Sound support is still basic, there is no spatialization available. This means, only sound volume will change, whether you are close or far to the sound, but panning (left, right) will not change if you rotate.

**Comment by create3000** [comment]
Think we can have spatialized Sound with next release.

**Comment by vralexllobet** [comment]
Thanks so much for the nice words about my site and also for working on the sound.  It's just a minor thing I noticed.
Your work in here is amazing!
I'm so happy to have found this site and that I'm able to now again show my VRML work that I started in 1999!
Hopefully I have some time and will up date my site and maybe port it to X3D.

**Comment by create3000** [comment]
Have right now released a new version 8.12.0 with spatialize sound.
