### ISSUE TITLE
TypeScript types for x_ite

### ISSUE THREAD

**Issue by gwhitney** [create3000/x_ite#152]
Given the number of folks that are using TypeScript these days, you might want to provide TypeScript typings for x_ite. The ideal would be for them to be automatically generated, but I am not sure how that would be accomplished (I tried checking out the repository and running `tsc --declaration --allowJs` but that failed badly). So another plan would be to hand-write a TypeScript .d.ts file with type declarations. I attach my initial effort at a comprehensive version of this, in case it will be of help. It surely is incomplete/has errors, but it does compile, and it works for the limited number of calls I am making at the moment.

One possibility is I could submit a PR to @DefinitelyTyped, but it would make more sense for the maintainers of this package to supply the typings. (And DefinitelyTyped does point out that it's clearer for packages to supply the types alongside their JavaScript packages.) I could also submit a PR with this .d.ts file, but as it is hand written it would not be clear to me where it should go so that it would be properly packaged with x_ite so that others using TypeScript could take advantage of it effortlessly.

Thank you for creating x_ite -- if I can be of any further assistance with providing TypeScript typings, please just let me know.
[x_ite.d.ts.txt](https://github.com/create3000/x_ite/files/12571737/x_ite.d.ts.txt)

**Comment by create3000** [comment]
https://github.com/create3000/x_ite/issues/116

**Comment by create3000** [comment]
I'm not that familiar with TypeScript, which means I can't maintain the declarations file either, which means a PR is always welcome.

**Comment by create3000** [comment]
I have already had a look at the .ts file, there are still a few small errors in there, but on the whole it already looks very good.

**Comment by create3000** [comment]
I put the .d.ts file in the list folder https://github.com/create3000/x_ite/tree/development/dist. I hope this is the right place. Can you please give me an example how I can benefit from this file.

**Comment by create3000** [comment]
I have tested the new file with VSCode and IntelliSense works fine for both JS and TS files. Thanks for your great efforts. If you have further updated, please let me know.

**Comment by gwhitney** [comment]
Well once it's in an x_ite published release, then thereafter I can just file PRs to this repository with any corrections/improvements that I may find. Thanks!

**Comment by create3000** [comment]
I can make a release next Sunday if all is fine, and we have still time for changes.

**Comment by create3000** [comment]
I have added you to the list of contributors in https://github.com/create3000/x_ite/blob/development/package.json, for that reason it is good idea to make a PR when the file has changed.

**Comment by create3000** [comment]
Version 8.12.1 is out now. Please drop me a note if it is working for you.

**Comment by gwhitney** [comment]
Oh dear, seems I overlooked responding -- yes, I am compiling and running fine with the latest version, now 8.12.4. Thanks!
