### ISSUE TITLE
Issue with model in X3D archives

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#153]
https://www.web3d.org/x3d-resources/content/examples/HumanoidAnimation/WinterAndSpring/Lily73Final0823Test2Index.html

Does not display well in x_ite well on website.  I don't know about downloading yet.

view3dscene fails to render in some cases, see:  https://github.com/castle-engine/view3dscene/issues/63

Thanks!

**Comment by create3000** [comment]
The problem with this model is, that a skin coordIndex is referenced up to 12 times in several HAnimJoint nodes. This is too much for a GPU accelerated humanoid. X_ITE only supports 4 references, as specified in glTF standard.

**Comment by coderextreme** [comment]
According to Michalis, the glTF has  a minimum of 4 references.  More may
be added to the glTF through additional extension objects.

Thanks!

John
