### ISSUE TITLE
npx sunrize [files]

### ISSUE THREAD

**Issue by vralexllobet** [create3000/x_ite#160]
I don't know if I'm using this correctly.
I'm trying to test the Sunrize editor so I paste "npx sunrize" into a CMD window in Windows but I get this error message...

'electron' is not recognized as an internal or external command,
operable program or batch file.

What to do?
Thanks!

**Comment by create3000** [comment]
I have tested it and it should work:

![console](https://github.com/create3000/x_ite/assets/2930196/cbe7a676-2ce2-4e0b-9559-5cdccbf2478a)

It is important that you have npm installed, but this should be enough. Make sure you have a recent version. Could you paste your console output here, please?

**Comment by vralexllobet** [comment]
This is what I get even after updating to the latest install...

![IKvQ7HJKD8pNlgOF](https://github.com/create3000/x_ite/assets/142753374/0add6cad-34ac-4cbf-9fb1-321d64215982)

**Comment by create3000** [comment]
Could you please once again try:

```console
npx sunrize@latest
```

In the meanwhile I do prepare a Windows installer, which is already working, but I would like to test it still a bit.

**Comment by vralexllobet** [comment]
This worked... npx sunrize@latest  
Thank you!
Now I see the Sunrize editor and am studying how to use it.

FYI, I've been creating models in AC3D 3D modeler and then exporting to VRMLPad by ParallelGraphics.
Yes, this stuff is really old but worked to build my worlds.
I hope to be able to edit in the more advanced X3D with greater functionality.
Thanks again!

**Comment by create3000** [comment]
If there are no further questions, I will close this issue now. Please feel free to reopen this issue again or open a new issue.
