### ISSUE TITLE
"aspectRatio" not supported?

### ISSUE THREAD

**Issue by davidhedley** [create3000/x_ite#162]
Trying to view some specific third party WRL models, x_ite-9.1.10 fails with:

```
    aspectRatio 0
                   ^
Unknown field 'aspectRatio' in class 'Panel'.

```
Can this property be supported or ignored?

**Comment by davidhedley** [comment]
Thanks for your response. So you are saying is it not possible to just warn on unknown fields and continue the parse? 
This is a snippet of the VRML:
```
  DEF SafeAreaFrame Switch 
   {
    choice 
    [ 
     DEF FrameGroup Group 
     {
      children 
      [ 
       DEF FP1 Panel 
       {
        source HTMLText 
        {
         body ""
         padding []
         shadow FALSE
         shadowTransparency 0
         shadowSize 8
         shadowOffset 3
         shadowColor 0 0 0
        }
        top "0"
        left "0"
        right ""
        bottom ""
        width "1"
        height "1"
        offsetLeft ""
        offsetTop ""
        aspectRatio 0
        sticky FALSE
        enabled FALSE
        backgroundTransparency 1
        backgroundColor 1 1 1
        borderSize 1
        borderRadius "0"
        borderColor 1 0 0
       }

```

If necessary I could preprocess the file to remove the offending line but I wasn't sure if this was something in the VRML standard that you might want to support?

**Comment by davidhedley** [comment]
On closer inspection there is a reference further up in the WRL to:
`["urn:inet:parallelgraphics.com:cortona:Panel" "http://www.parallelgraphics.com/vrml/proto/Cortona/extensions.wrl#Panel"]`
I can see this is failing to load as part of the parse (CORS issues) which I assume is leading to the error shown above.

Thanks for your speedy response - looks like I need to fix this elsewhere.

**Comment by create3000** [comment]
Think we can have it with next version, ie. unknown nodes and fields will be ignored during parse, but there will be at least a warning, that there was something unknown.
