### ISSUE TITLE
Despite no errors on the console, X_ITE shows no graphics 

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#163]
The graphics on this site do not render, just images

https://coderextreme.net/X3DJSONLD/src/main/html/personal.html

Thanks for any assistance.

i have tried at least a few in X3D-Edit.  There might be an issue with http/https missing.

Many work well in FreeWRL/Octaga.

john

**Comment by coderextreme** [comment]
https://create3000.github.io/x_ite/ shows that I can enable debugging, impressive change!

**Comment by coderextreme** [comment]
I see few debugging assistance messages.  Hmm.  Here's the log:


Initializing UnlitShader
x_ite.min.js:1 1704490124.09
x_ite.min.js:1 Initializing UnlitShader
x_ite.min.js:1 Initializing PhongShader
x_ite.min.js:1 Initializing UnlitShader
x_ite.min.js:1 Initializing PhongShader
x_ite.min.js:1 1704490125.345
2x_ite.min.js:1 Initializing UnlitShader
x_ite.min.js:1 Initializing PhongShader
x_ite.min.js:1 Initializing GouraudShader
x_ite.min.js:1 1704490126.245
x_ite.min.js:1 1704490127.228
x_ite.min.js:1 1704490128.242
x_ite.min.js:1 1704490129.215
x_ite.min.js:1 1704490130.194
x_ite.min.js:1 1704490131.269
x_ite.min.js:1 1704490132.239
x_ite.min.js:1 1704490133.188
x_ite.min.js:1 1704490134.249
x_ite.min.js:1 1704490135.222
x_ite.min.js:1 1704490136.254
x_ite.min.js:1 1704490137.265
x_ite.min.js:1 1704490138.219
x_ite.min.js:1 1704490139.266
x_ite.min.js:1 1704490140.21
x_ite.min.js:1 1704490141.247
x_ite.min.js:1 1704490142.218
x_ite.min.js:1 1704490143.201
x_ite.min.js:1 1704490144.256
x_ite.min.js:1 1704490145.239
x_ite.min.js:1 1704490146.287
x_ite.min.js:1 1704490147.181
x_ite.min.js:1 1704490148.248
x_ite.min.js:1 1704490149.197
x_ite.min.js:1 1704490150.247
x_ite.min.js:1 1704490151.209
x_ite.min.js:1 1704490152.181
x_ite.min.js:1 1704490153.236
x_ite.min.js:1 1704490154.211
x_ite.min.js:1 1704490155.265
x_ite.min.js:1 1704490156.219
x_ite.min.js:1 1704490157.216
x_ite.min.js:1 1704490158.184
x_ite.min.js:1 1704490159.246
x_ite.min.js:1 1704490160.274
x_ite.min.js:1 1704490161.242
x_ite.min.js:1 1704490162.228
x_ite.min.js:1 1704490163.262
x_ite.min.js:1 1704490164.218
x_ite.min.js:1 1704490165.253
x_ite.min.js:1 1704490166.2
x_ite.min.js:1 1704490167.222
x_ite.min.js:1 1704490168.265
x_ite.min.js:1 1704490169.23
x_ite.min.js:1 1704490170.226
x_ite.min.js:1 1704490171.268
x_ite.min.js:1 1704490172.219
x_ite.min.js:1 1704490173.242
x_ite.min.js:1 1704490174.205
x_ite.min.js:1 1704490175.246
x_ite.min.js:1 1704490176.185
x_ite.min.js:1 1704490177.262
x_ite.min.js:1 1704490178.195
x_ite.min.js:1 1704490179.221
x_ite.min.js:1 1704490180.254
x_ite.min.js:1 1704490181.244
x_ite.min.js:1 1704490182.182
x_ite.min.js:1 1704490183.209
x_ite.min.js:1 1704490184.244
x_ite.min.js:1 1704490185.276
x_ite.min.js:1 1704490186.224
x_ite.min.js:1 1704490187.262
x_ite.min.js:1 1704490188.221
x_ite.min.js:1 1704490189.205
x_ite.min.js:1 1704490190.242
x_ite.min.js:1 1704490191.269
x_ite.min.js:1 1704490192.23
x_ite.min.js:1 1704490193.189
x_ite.min.js:1 1704490194.247
x_ite.min.js:1 1704490195.243
x_ite.min.js:1 1704490196.236
x_ite.min.js:1 1704490197.229
x_ite.min.js:1 1704490198.22
x_ite.min.js:1 1704490199.233
x_ite.min.js:1 1704490200.231
x_ite.min.js:1 1704490201.248
x_ite.min.js:1 1704490202.231
x_ite.min.js:1 1704490203.281
x_ite.min.js:1 1704490204.18
x_ite.min.js:1 1704490205.189
x_ite.min.js:1 1704490206.187
x_ite.min.js:1 1704490207.274
x_ite.min.js:1 1704490208.255
x_ite.min.js:1 1704490209.239

I'm going to try Firefox and Chrome

**Comment by coderextreme** [comment]
Despite above attempts, still no progress.

Hmm. My next step is getting into source code add debugging.

I've tried Edge, Chrome and Firefox.

**Comment by coderextreme** [comment]
I've also tried changing X3D versions to 4.0

**Comment by coderextreme** [comment]
I'm going to submit these as separate issues.

**Comment by create3000** [comment]
Your extrusion.x3d cannot work, because you made a mistake in your script:

```js
function set_cycle(value) {
   Browser.print(value);
   var endA = new SFVec3f(spine[0].x*Math.random()*2, spine[0].y*Math.random()*2, spine[0].z*Math.random()*2);
   var endB = new SFVec3f(spine[1].x*Math.random()*2, spine[1].y*Math.random()*2, spine[1].z*Math.random()*2);
   // The arguments for MFVec3f should be without bracket.
   spine = new MFVec3f([endA, endB]);
}
```

See https://create3000.github.io/x_ite/reference/field-services-and-objects/#mfvec3dmfvec3df-object
Please note that bracket in the documentation denote that this argument(s) are optional.

**Comment by coderextreme** [comment]
Dang, I was going to try that.  Apologies for not following through .  I
hope your solution works for the other browsers as well.

I will close the issue, and try tonight.

Thanks!

**Comment by coderextreme** [comment]
I think I have to do this:

let tmpspine = new MFVec3f();

tmpspine[0] = endA; // or .append()/.push()

tmpspine[1] = endB; // ditto

spine = tmpspine;

to achieve some kind of atomicity and portability.

I haven’t tested the above, but I recall wrestling with this problem before.

**Comment by create3000** [comment]
Please let me know, if you could solve your problem.

Also have a look into the JavaScript API documentation for MFVec3f at Web3D.org https://www.web3d.org/documents/specifications/19777-1/V3.3/Part1/functions.html#MFVec3f

**Comment by coderextreme** [comment]
Yes, keeping a tmp variable patched one case.  …array may be a solution for
modern JavaScript.

I got stuck handling 100x100 MFVec3f in FreeWRL.   I’m guessing …array and
modern JavaScript would have fixed the problem, but I ended up using a
Script <field> and duktape JS.  I have not tried …array with duktape.

…array works ok in sunrize in my other case.
