### ISSUE TITLE
ExternProtoDeclare not downloading?  X3D checks in X3D-Edit.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#165]
https://coderextreme.net/X3DJSONLD/src/main/html/x_iteflowers.xhtml

JSON version downloads here:

https://coderextreme.net/X3DJSONLD/src/main/html/indexts.html

Although there seems to be downloads that don't succeed.

![image](https://github.com/create3000/x_ite/assets/705783/dd278870-f1db-4510-ac25-a7813938db5b)

**Comment by coderextreme** [comment]
This works:  https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoExamplesIndex.html

So maybe not an issue with downloading ExternProtoDeclare?  I'm clueless. I will have to go somewhere else to think.

**Comment by coderextreme** [comment]
In Sunrize:

sphereflowers.x3d:

![image](https://github.com/create3000/x_ite/assets/705783/29a27a42-1c22-4295-b145-a73ed419ad40)

sphereflowers.json:

![image](https://github.com/create3000/x_ite/assets/705783/4455480a-c431-483f-a070-d934b6233424)

Turning on animation and sound works great in Sunrize (I could capture video), so there's probably something I need to do to start animation in X_ITE? I'm not sure why my index.html works then.  Maybe add a way to turn on animation and sound in the X_ITE menu?  Thanks!

**Comment by create3000** [comment]
This is due a bug in Chrome, when the page is a XHTML page, as in your case. Because X_ITE uses the Custom Elements API, Chrome does not forward the attributes of the custom element as the API requires. If you can, pleas file a bug at the Crome bug report page.

As workaround convert your XHTML to a modern HTML 5 page.
