### ISSUE TITLE
Mono Sound plays only over left speaker

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#166]
When I use a Sound node in VRML and use a mono .wav file, I noticed that the sound only plays from the left speaker.
It used to be playing from both speakers.

If I use a tool (Audacity in my case) to convert the .wav to stereo it plays fine.

X_ITE: 9.3.1
Windows 10
Google Chrome

Thanks, Olaf

**Comment by create3000** [comment]
This is now fixed. If everything looks good, then I will release a new version on Sunday.

**Comment by olafgithub** [comment]
Perfect!

Thanks,
Olaf

**Comment by create3000** [comment]
New version 9.3.2 is out now.
