### ISSUE TITLE
"Better" webpack.config.js, for Git Bash under Windows 10

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#168]
[webpack.config.js.txt](https://github.com/create3000/x_ite/files/15091852/webpack.config.js.txt)

I had never really seen | used for a perl substitution s|...|...| operator before.  Just to let you know, when you put that inside backticks, `, inside a webpack config, that's asking for trouble!

See link for "improved" version.  Test on your system, please.

I am running ```webpack``` with no options right now.

That's pretty much all I can deal with other people's bugs for today.

Thanks for creating a great system with X_ITE and Sunrize.  I can work on testing your build systems for Windows 10 and Git Bash.

John

**Comment by coderextreme** [comment]
I’m thinking that using node.exe instead of node on windows may solve a few issues

**Comment by create3000** [comment]
The module config and build scripts are not made to run on Windows, it is made to run on macOS, and maybe Linux.

**Comment by coderextreme** [comment]
Bummer that. WSL2 is Linux 5.X kernel

**Comment by coderextreme** [comment]
I do think there might be some issues in my Windows version where the
output files are filled with comments
