### ISSUE TITLE
Replace webpack "string-replace-webpack-plugin" or provide dependency overrides in package.json

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#169]
Try to replace this module as it is gathering CVEs from json5 and related node/webpack modules.

I'm experimenting with this in my development package.json:
```
-       }
+       },
+         "overrides": {
+           "json5": "^1.0.2",
+            "css-loader": "^7.1.1",
+            "file-loader": "^6.2.0",
+            "style-loader": "^4.0.0",
+            "loader-utils": "^1.4.2"
+         }
```
Thanks!

John

**Comment by create3000** [comment]
With what can I replace this plugin?

**Comment by coderextreme** [comment]
“Or” means an alternative. Try using overrides in package.json.

I’ve had success, but I’m not doing extensive options to webpack.

John
