### ISSUE TITLE
IndexedFaceSet solid false and alpha

### ISSUE THREAD

**Issue by Wagyx** [create3000/x_ite#173]
Hello there,
I have developed an OFF file parser and I think I am seeing issues with color alpha in IndexedFaceSet.
I am using IndexedFaceSet for the faces, with solid=false, convex=false, colorPerVertex=false.
Here is the result that I get when I use a Color node:
![Capture_rgb](https://github.com/create3000/x_ite/assets/6882329/4cfb2377-f3ee-46b5-a9fb-8da3d51e6359)
Here is the result when I use an ColorRGBA node with an alpha value of 1:
![Capture_rgba](https://github.com/create3000/x_ite/assets/6882329/42a16ee6-7d5d-45ac-933e-48af288ec016)
The expected behaviour would be that the pictures be the same.
There could also be something that I don't understand about alpha and double sided faces.
Let me know what you think.
Thank you

**Comment by create3000** [comment]
If a ColorRGBA node is used, the Shape node is treated as transparent. Especially if you use more then one Shape, and these shapes are overlapping, it can be possible to get some unexpected results. But you can control the alpha behavior with `Appearance.alphaMode` and `Appearance.alphaCutoff`. 
https://create3000.github.io/x_ite/components/shape/appearance/#sfstring-in-out-alphamode-auto-autoopaquemaskblend
