### ISSUE TITLE
unable to open local world

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#22]
edited "x_ite-4.2.4/example.html" for all local use. 

(BTW why does this example have remote resource files, when they are downloaded in the zip and are in the same folder?)

```
<!DOCTYPE html>
  <html>
   <head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="x_ite.css"/>
    <script type="text/javascript" src="x_ite.js"></script>
    <style>
    X3DCanvas {
      width: 1000px;
      height: 563px;
    }
    </style>
  </head>
  <body>
    <X3DCanvas src="../test2.wrl">
      <p>Your browser may not support all features required by X_ITE!</p>
    </X3DCanvas>
  </body>
</html>
```

browsers firefox and chrome fail and produce error;

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/simon/Downloads/x_ite/test2.wrl. (Reason: CORS request not http).
```

**Comment by andreasplesch** [comment]
http://create3000.de/x_ite/getting-started/

has a fuller explanation. You need to serve from a web server.

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#Running_a_simple_local_HTTP_server

**Comment by splace** [comment]
yes, i did originally think it should be a feature request, but......

* the error reported is "...reading the remote resource at...", which is of-course just wrong.
* i believe it to be wider practice on the web that this works, cf HTML and X3DOM, doing it the same way allows leveraging more existing code/work. (certainly for me)
* setting up a server for casual use cases, is asking too much of the user. 
* seems to me, but i haven't tested, trivial to do it better. my guess is; try a non-CORS request first, and if that fails only then try the more advanced CORS request.

where i'm coming from;

i do grok what an evolving/historical mess getting data on web-pages is.
but servers are a blockage, distributed, non-server based, web tech, is generally the way forward. 
for example; web-sockets being used to syncing up worlds between browsers, has huge potential.

**Comment by create3000** [comment]
CORS is a browser security feature.
You CAN open local files in firefox (and only in firefox) if you keep some things in mind.
* all files must be in the same folder
* the web page is in the main folder
* x3d, images ... must be in the main folder or subfolder

**Comment by splace** [comment]
> CORS is a browser security feature.

you are mis-informed

CORS is Cross Origin Resource Sharing, its a way to BYPASS the, clumsy,  security restriction of only allowing resources from the same origin.

**Comment by splace** [comment]
i will try using that setup with firefox.

(sorry, previous comment a bit terse, i was cooking for kids simultaneously.)

**Comment by splace** [comment]
able to open local files this way. closing.

**Comment by splace** [comment]
turns out x_ite does support .wrl see #24

**Comment by brutzman** [comment]
Now that X3D-Edit 4.0 is running (in beta) again, am looking for a simple way to add a CORS option using Java so that authors can use X_ITE on locally converted models. [https://savage.nps.edu/X3D-Edit](https://savage.nps.edu/X3D-Edit)
![image](https://user-images.githubusercontent.com/7712992/118383697-30f4f500-b5b5-11eb-99ce-5adc5436335f.png)
