### ISSUE TITLE
showing files being downloaded that arn't

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#23]
when loading a world with 32 instances of a prototype, loading screen says downloading 32 files.

**Comment by create3000** [comment]
This is the correct behavior. Think it would be better to display "Downloading 32 Objects".

**Comment by splace** [comment]
do not really understand your sentences' meaning.

in-case you misunderstand me;

this is happening for INSTANCES of a local prototype, no loading whatsoever, there could be thousands. this makes no sense, why confuse the user, why display anything under these circumstances?

**Comment by create3000** [comment]
This should be fixed in the next version.
