### ISSUE TITLE
x_ite js files from 'code.create3000.de' are corrupt

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#25]
the files below cause a syntax error due to a couple of corrupt characters;

https://code.create3000.de/x_ite/latest/dist/x_ite.js  line 13659
https://code.create3000.de/x_ite/4.2.4/dist/x_ite.js
and min versions.
(no other version or sources checked)

file in zip is OK.

**Comment by splace** [comment]
as a work round, file here;

https://rawgit.com/create3000/x_ite/master/dist/x_ite.js

is not corrupt.

**Comment by splace** [comment]
sorry but that also has corrupt characters, further down the file, line 50098

````
// Transform the point by the matrix
			matrix .multá¸¾atrixVec (point);
````

**Comment by create3000** [comment]
Fixed that typo.
Please double check again.

**Comment by splace** [comment]
that's working

**Comment by create3000** [comment]
Thanks for double checking because I could not reproduce this in any browser. Hopefully X_ITE is now free from stray characters.

**Comment by splace** [comment]
unfortunately the origin links are still corrupt, and they are in the docs.

this reported also here #

**Comment by splace** [comment]
rechecked;

https://code.create3000.de/x_ite/latest/dist/x_ite.js and .../x_ite.min.js   are now good

but

https://code.create3000.de/x_ite/4.2.4/dist/x_ite.js and .../x_ite.min.js   are still corrupt.

**Comment by splace** [comment]
confirmed ALL versions now fine on this domain.

**Comment by splace** [comment]
seems to have come back, (or i checked the wrong one.)

https://code.create3000.de/x_ite/4.2.4/dist/x_ite.js (and .../x_ite.min.js)  is corrupt, couple of odd chars, as before.

4.2.5 is OK.

**Comment by splace** [comment]
[for info] rechecked, and 4.2.4 still has the corruption, but newer releases dont.

bit out of date really so closing.
