### ISSUE TITLE
[info] chrome wont play sounds at first.

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#29]
some sort of ad blocking? firefox is fine.

guess this 'feature' might become standard practice or might just go away.

chrome log....
````
x_ite.min.js:33 Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
````
useful link...

https://stackoverflow.com/questions/49930680/how-to-handle-uncaught-in-promise-domexception-play-failed-because-the-use

**Comment by create3000** [comment]
As the log shows, there is an explanation why. https://goo.gl/xX8pDD Using the AudioClip node or MovieTexture node is not other than using a audio or video tag and X3D authors must respect the browser issues.

**Comment by splace** [comment]
> ....  X3D authors must respect the browser issues.

IMO authors can't be expected to do this and don't need to be made too, X-ITE should check sound is being suppressed and then display a message.

**Comment by splace** [comment]
FYI not sure when/why but seems fine now.
