### ISSUE TITLE
triangulation of concave face fails when face has coincident point(s).

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#30]
this shape shows a missing triangle. (works in Titania.)
guess would be 'convex' issue

````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D profile='Interchange' version='3.0' xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' xsd:noNamespaceSchemaLocation='http://www.web3d.org/specifications/x3d-3.0.xsd'>
  <Scene>
    <Shape DEF='body'>
      <Appearance>
        <Material/>
      </Appearance>
      <Extrusion
          convex='false'
          crossSection='0 -0.5, -0.1 -0.5, -0.184776 -0.18696, -0.184776 0.18696, -0.1 0.5, -0.1 0.5, 0 0.5, 0.15 0.3, 0 0.25, 0 -0.25, 0.15 -0.3, 0.136798 -0.336543, 0 -0.5'
          />
    </Shape>
  </Scene>
</X3D>
````

**Comment by create3000** [comment]
If you look closer at your cross section you will notice that point 5 and 6 are the same.

```
  0 -0.5,
  -0.10000000149011612 -0.5,
  -0.18477599322795868 -0.18695999681949615,
  -0.18477599322795868 0.18695999681949615,
  -0.10000000149011612 0.5,
  -0.10000000149011612 0.5,
  0 0.5,
  0.15000000596046448 0.30000001192092896,
  0 0.25,
  0 -0.25,
  0.15000000596046448 -0.30000001192092896,
  0.13679799437522888 -0.3365429937839508,
  0 -0.5
```

Clause 13.3.6 IndexedFaceSet http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/geometry3D.html#IndexedFaceSet describes what a polygon is:

Each face of the IndexedFaceSet shall have:

1. at least three non-coincident vertices;
2. vertices that define a planar polygon;
3. vertices that define a non-self-intersecting polygon.

Otherwise, The results are undefined.

These rules for a polygon will also be relevant for begin and end cap polygons of an Extrusion node. Your cross section breaks rule 1 in that, that there should be no non-coincident points. The result will differ from implementation to implementation.

**Comment by splace** [comment]
> Your cross section breaks rule 1 in that, that there should be no coincident points.

'at least three non-coincident vertices' means there can be ANY number of coincident vertices, as long as there are three, or more, that are not, my cross-section is passing this rule.

**Comment by splace** [comment]
see this;

http://www.web3d.org/x3d/content/ConformanceNist/Geometry/Extrusion/test_convexIndex.html

**Comment by splace** [comment]
forget the conformance test, its corrupt/broken in an unrelated way, (it was self-intersecting!!), when 'fixed-up' both Titania and X_ite are fine with it.

````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE X3D PUBLIC "ISO//Web3D//DTD X3D 3.0//EN" "http://www.web3d.org/specifications/x3d-3.0.dtd">
<X3D profile='Immersive' version='3.0'  xmlns:xsd='http://www.w3.org/2001/XMLSchema-instance' xsd:noNamespaceSchemaLocation =' http://www.web3d.org/specifications/x3d-3.0.xsd '>
<head>
</head>
<Scene>
<Shape>
<Appearance>
<Material/>
</Appearance>
<Extrusion convex='false' crossSection='
1 0
9 -4
7 -7
4 -9
0  0
-3 -10
-6 -8
-9 -5
-10 -2
-10 2
-8.5 5
-6 8 
-3 10
1 10
4.5 9
7 7
9 4 
1 0' solid='false'/>
</Shape>
````

**Comment by splace** [comment]
same shape as a IFS face, does the same..

````
  <Scene>
    <Shape DEF='body'>
      <Appearance>
        <Material/>
      </Appearance>
      <IndexedFaceSet
          convex='false'
          coordIndex='0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, -1'>
        <Coordinate
            point='0 -0.5 0, -0.1 -0.5 0, -0.184776 -0.18696 0, -0.184776 0.18696 0, -0.1 0.5 0, -0.1 0.5 0, 0 0.5 0, 0.15 0.3 0, 0 0.25 0, 0 -0.25 0, 0.15 -0.3 0, 0.136798 -0.336543 0, 0 -0.5 0'/>
      </IndexedFaceSet>
    </Shape>
  </Scene>
````

**Comment by splace** [comment]
same if the coincident point is supplied by ref (index) rather than duplicated values.

**Comment by create3000** [comment]
![bildschirmfoto vom 2018-10-06 03-43-44](https://user-images.githubusercontent.com/2930196/46566191-2ca2ce80-c91a-11e8-827b-d34e497d77d0.png)

**Comment by splace** [comment]
works for me.
