### ISSUE TITLE
not playing mpeg 1 movie

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#32]
i guess due to lack of browser movie support.

should Titania also not support in compatibility mode?

**Comment by create3000** [comment]
> i guess due to lack of browser movie support.

This is true, X_ITE can only play movies the browser supports by <video> tag.

> should Titania also not support in compatibility mode?

I cannot disable only MPEG movies, video is supported by libav.

**Comment by splace** [comment]
>  I cannot disable only MPEG 1 movies, video is supported by libav.

well i just meant a message saying 'not supported by x_ite' and a roll back, when the compat. mode is on and when the new url data shows it to be mpeg1.

**Comment by create3000** [comment]
X3D authors using web browsers should be aware what video formats a web browser can play. X_ITE cannot properly detect the video format, that's up to the browser.

**Comment by splace** [comment]
how does an author, writing/playing complaint VRML, know that X_ITE is not doing its own decoding. i see mpeg1 decoders in JS available.
