### ISSUE TITLE
extrusion cross-section orientations wrong

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#33]
test file; [extru-orient-bug.zip](https://github.com/create3000/x_ite/files/2521092/extru-orient-bug.zip)

correct rendering AFAICT (screenshot from view3dscene)

![scene_0](https://user-images.githubusercontent.com/1234848/47594780-c5a29380-d974-11e8-9b05-34b69bbe0a81.png)

note: red pyramids can be facing left or right, spec. doesn't indicate which is right.

**Comment by splace** [comment]
test file details; 

all extrusions, all with two-point splines fanning out from the centre, all roughly the same length, all with the same triangular cross-section, all with the same orientations designed to cause the points of the triangular cross-sections to roughly meet.  this should make rectangular based pyramids pointing circumferentially and aid visualisation of orientation.

**Comment by create3000** [comment]
Released new version.

**Comment by splace** [comment]
fixed
