### ISSUE TITLE
SAI generated Scene does not load

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#34]
although it does after going through the XML encoding.

```
//browser.replaceWorld(scene); \\ does not work
browser.replaceWorld(browser.createX3DFromString(scene.toXMLString())); \\ works
```

https://github.com/andreasplesch/Library/blob/gh-pages/Examples/Dolphin/flipp_sai.html

There may be only a little trigger missing somewhere.

**Comment by andreasplesch** [comment]
Here is a minimal example: https://raw.githack.com/andreasplesch/Library/gh-pages/Examples/Dolphin/sai_test.html

This scene construction does not seem to work:
```js
         var browser = X3D.getBrowser(document.querySelector('X3DCanvas'));
         var scene = browser.createScene();
         var bg = new X3D.SFNode(scene.createNode('Background', false));
         bg.skyColor = X3D.MFColor(X3D.SFColor(0, 0, 1));
         scene.rootNodes.push(bg);
         browser.replaceWorld(scene);//does not work
         //browser.replaceWorld(browser.createX3DFromString(scene.toXMLString()));//works
```

**Comment by andreasplesch** [comment]
It turns out I was overthinking it. .createNode(nodename) without the ,false already creates the SFNode wrapper and also sets the node fields up properly. So this works:
```js
         var browser = X3D.getBrowser(document.querySelector('X3DCanvas'));
         var scene = browser.createScene();
         var bg = scene.createNode('Background');
         bg.skyColor = X3D.MFColor(X3D.SFColor(0, 0, 1));
         scene.rootNodes.push(bg);
         browser.replaceWorld(scene);//works now
         //browser.replaceWorld(browser.createX3DFromString(scene.toXMLString()));//also works
```

**Comment by create3000** [comment]
I am happy to hear that the SAI interface works properly. It is important that the same browser (canvas) is used for displaying and creation of nodes. The extra boolean argument of X3DScene.createNode is only for internal use, just use createNode as in the spec.
Best regards, Holger.
