### ISSUE TITLE
focusing X3DCanvas element doesn't allow viewpoint navigation

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#36]
seem to always need to click on scene for it to get focus and have pgup/dn navigation. 

ex. this isn't working as expected.
```` xml (not working)
  <X3DCanvas src="scene.wrl" onLoad="this.focus()">
      <p>Your browser may not support all features required by X_ITE!</p>
    </X3DCanvas>
````

**Comment by create3000** [comment]
Try using a timer, but in the body element:
https://stackoverflow.com/questions/1096436/document-getelementbyidid-focus-is-not-working-for-firefox-or-chrome

`<body onload="setTimeout (function () { document.querySelector('X3DCanvas').focus () }, 1000);">`

**Comment by create3000** [comment]
The X3DCanvas element does not have a onload attribute, but you can use:

```
function browserCallback (event)
{
  switch (event)
  {
    case 'initialized':
      break;
  }
}

X3D (function ()
{
  var Browser = X3D .getBrowser ("X3DCanvas");
  
  Browser () .addBrowserCallback (this, browserCallback);
});
```

See also:
http://create3000.de/users-guide/ecmascript-object-and-function-definitions/browser-services/
http://create3000.de/x_ite/accessing-the-external-browser/

**Comment by splace** [comment]
thanks, i will look at ways to do this.
