### ISSUE TITLE
not using available audio file url after first url missing.

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#37]
see;

http://www.web3d.org/x3d/content/examples/ConformanceNist/Sounds/AudioClip/multi_url.x3d

from/in;

http://www.web3d.org/x3d/content/ConformanceNist/Sounds/AudioClip/multi_urlIndex.html

**Comment by create3000** [comment]
What do you think what it is not working with this example. Tested and AudioClip MYSOUND1 with url "chimes.wav" works and AudioClip MYSOUND3 with url "nonexistent.wav" does not work, because it cannot work, because the file does not exits.

**Comment by splace** [comment]
the description of the test says;

> This file tests the ability of a browser to skip a nonexistent URL and proceed to the next url in the list to load a sound file.

so it SAYS the second button should sound, but it doesn't, however looking at the code it actually shouldn't, the test is broken!  as a guess there was once a MYSOUND2, now missing, that was the actual test!

looks like i'm going to have to assume all these tests are unreliable, see previously: https://github.com/create3000/x_ite/issues/30#issuecomment-427069301

i added a findable sound url after the non-findable one, and that works, in Titania.

(however there is some issue, i was investigating, with loading a sound file, when i checked the conformance test and found it didn't work, i thought this must have something to do with it, i'll go back and check some more.)

**Comment by splace** [comment]
see https://github.com/create3000/titania/issues/68#
