### ISSUE TITLE
node.dispose() sometimes never returns

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#40]
I am now getting an infinite loop when I click 'remove box' here:

https://andreasplesch.github.io/x_ite_dom/index.xhtml

This simply calls node.dispose() which then enters an infinite loop.

Maybe I can come up with a pure x3d example. https://github.com/create3000/x_ite/issues/40#issuecomment-471368234

**Comment by andreasplesch** [comment]
node.dispose() seems to work fine in a regular script:

https://gist.github.com/andreasplesch/a70a5544ce291e1d2708d0a7ec52746c

https://gist.githack.com/andreasplesch/a70a5544ce291e1d2708d0a7ec52746c/raw/bff957ea823621b7782366f2e7383ff70d05a6f3/x_ite.html

It returns and nulls the node. (But the scenegraph may not be updated).

So something else, investigating.

**Comment by andreasplesch** [comment]
This for of loop keeps sometimes looping forever:

https://github.com/create3000/x_ite/blob/082f4e8ba2202c81950519cabb64926947730a6e/src/x_ite/Basic/X3DBaseNode.js#L1048

**Comment by andreasplesch** [comment]
Apparently, the never ending iterator has to do how the map is modified while being iterated. When I copy the parents map first to a new Map, the loop finishes and the node is disposed:

```var firstParents = new Map(this .getParents ());```

But of course I am not sure if this is correct.

**Comment by andreasplesch** [comment]
Ok, I found that this test example

https://github.com/create3000/Library/blob/master/Tests/Components/Scripting/BaseNodeDispose.x3d

has the same issue. Clicking on the dispose box results in the infinite loop. Here a live scene:

https://gist.githack.com/andreasplesch/a70a5544ce291e1d2708d0a7ec52746c/raw/69a202d334e7c4b149c717caa4ac7bdb271e9f68/x_ite.html

**Comment by create3000** [comment]
Fixed this in latest release and 'parents' are now a Set. 'Remove Box' in now working.

**Comment by andreasplesch** [comment]
Thanks. I can confirm. Here is the test example updated to the latest release:

https://gist.githack.com/andreasplesch/a70a5544ce291e1d2708d0a7ec52746c/raw/cc52ea343e32dad8b18d23fd21940b6503d2ddfd/x_ite.html

[Since parents are objects, perhaps it is possible to use WeakSet for better garbage collection. Just an idea.]
