### ISSUE TITLE
Chrome not running X-ITE

### ISSUE THREAD

**Issue by lawriehodges** [create3000/x_ite#45]
I've downloaded X-ITE 4.5.6. and attempted to run the example given in the section 'Embedding X-LITE within a Web Page'. This runs in Firefox, Cyberfox and Safari but NOT in Chrome (my default browser) or IE11. I have what I am told is the latest version Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by lawriehodges** [comment]
I see further down your web page, warnings that Chrome doesn't work locally without some sort of knudge that I couldn't really understand. I have put up  a section containing a .wrl world remotely on my web site and Chrome IS able to cope with that.

**Comment by create3000** [comment]
Did you run the example through a web server, for instance 'localhost' or using the 'file:' scheme? There is also an article how to run X_ITE on Chrome, see http://create3000.de/x_ite/getting-started/#using-google-chrome-and-opera-with-local-files.
