### ISSUE TITLE
VRML Inline nodes

### ISSUE THREAD

**Issue by lawriehodges** [create3000/x_ite#46]
I have a VRML2 world that contains three Inline nodes. This still works as it was originally created locally in Cortona3D and IE11. However, when it is included in an X-ite wrapper and run locally or remotely, only the first Inline appears. the second and third do not.

**To Reproduce**
1. Go to 'http://lhodges.users37.interdns.co.uk/me/xcard2/waddl_ard.htm'
2. Click on 'the still picture'

**Expected behavior**
The still picture shows approximately what should be seen. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome, Firefox, Cyberfox, Basilisc
Also: there is no sound with Firefox or Cyberfox and Safari does not load at all.

**Additional context**
Here is the beginning of the VRML2  world:

#VRML V2.0 utf8	jigH.wrl V0.1
WorldInfo {
	title "Jig for HP machines"
	info ["Lawrence C.Hodges 10th December 2000
	 "]
}

NavigationInfo {
	type	[ "FLY", "WALK", "EXAMINE", "ANY"]	
	headlight		FALSE
}

# -------------------- model ---------------------
Inline { 
	url "dancer.wrl"
}

Inline { 
	url "musician.wrl"
}

Inline { 
	url "ground.wrl"
}

**Comment by splace** [comment]
i took a look (just another user) and checking the console output....

```
Couldn't load URL 'http://lhodges.users37.interdns.co.uk/me/xcard2/musician.wrl': 
********************************************************************************
Parser error at line 40:7
in 'http://lhodges.users37.interdns.co.uk/me/xcard2/musician.wrl'


	level [
      ^
Unknown field 'level' in class 'LOD'.
********************************************************************************
x_ite.min.js:20:18440
Couldn't load URL 'http://lhodges.users37.interdns.co.uk/me/xcard2/ground.wrl': 
********************************************************************************
Parser error at line 11:7
in 'http://lhodges.users37.interdns.co.uk/me/xcard2/ground.wrl'


	level [
      ^
Unknown field 'level' in class 'LOD'.
********************************************************************************
```

seems the files aren't loaded because the 'level' field of LOD isn't recognised.

this has to be the result of the fields' name being changed, to 'children' between V2 (vrml) and V3 (x3d), but 'level' should be supported in a vrml2 file, so it is a bug.

i would guess you could cure, now, by changing the field name. (and ideally change the header in the files where the name was changed to have a header '#X3D V3.0 utf8')

Alternatively;

because LOD is an optimisation and given the advances in computer rendering, any vrml2 world isn't going to noticeably benefit, that is, the world will almost certainly render fine with just the highest level of the Level Of Detail's, so they could just be removed. (replaced with just what is inside the first level.)

**Comment by create3000** [comment]
Your file begins with the following header statement:
`#VRML V2.0 utf8	musician.wrl V0.1`
There is a 'tab' character after 'utf8' which is not recognized by the parser, change it to a 'space' character and it will work. I have also changed the parser, thus it will work in further versions of X_ITE.

You can get additional debug information when you go over an empty space of the web page and select 'Inspect Element' from the menu, then click on 'Console'. The Console shows additional debug information.

**Comment by create3000** [comment]
Note: you have used LOD's without a _range_ field, ie. it depends on the performance of the browser which level is displayed. Reading the spec:

> An empty range field is an exception to this rule. This case is a hint to the browser that it may choose a level automatically to maintain a constant display rate.

**Comment by create3000** [comment]
Why audio does not play see #29, and https://goo.gl/xX8pDD. in short: audio does not automatically play on load, it requires user interaction, you must make a button and click to start play audio.

**Comment by lawriehodges** [comment]
Thank you both.  I have looked your suggestions and acted on some of them. I have the model working reasonably in Chrome. Difficulties in testing arise from caching, which acts confusingly by loading old file versions when a new version has been provided. In Chrome I was able to get round this by loading a New Incognito Window . Having cleared the cache and allowed music to auto start it now works also in Firefox. The limitations are now in my model, rather than in the interactions with servers and browsers. It is twenty years since I wrote this and I have forgotten most of the code and the logic behind it. I have only come back to it when trying to repair the holes in my old, outdated website.

**Comment by splace** [comment]
> Difficulties in testing arise from caching, which acts confusingly by loading old file versions when a new version has been provided.

page refresh; keyboard shortcut "F5" or "Ctrl+F5" to bypass cache.

**Comment by lawriehodges** [comment]
Thanks for that.
In Chrome, I found: Settings | Advanced | Privacy and security | Clear browsing data, Check Cached images and files | Clear data

Well buried!

In Firefox: in top right menu: Options | Privacy and Security | Cookies and Site Data | Clear Data. Check Cached Web Content and uncheck Cookies and Site Data | Clear.

**Comment by create3000** [comment]
There is an 'Empty Cache' extension for Firefox https://addons.mozilla.org/en-US/firefox/addon/empty-cache-button/ maybe there is something similar for Chrome.

**Comment by lawriehodges** [comment]
Thank you. I have added it. And, there is something similar for Chrome:
https://chrome.google.com/webstore/detail/clear-cache-shortcut/jnajhcakejgchhbjlchkfmdidgjefleg/related?hl=en
