### ISSUE TITLE
X_CIT gives error that it doesn't recognize the Script node

### ISSUE THREAD

**Issue by billy-castle** [create3000/x_ite#48]
**Describe the bug**
lamppost is a lamp that you turn on or off by clicking on it. But when I load it into an X_ITE window, it reports an error: "XML Parser Error: Unkown node type 'Script'."

**To Reproduce**
Look at attached file lamppostxi.txt, and convert it to lamppostxi.x3d and open it using an X_ITE in the regular way. Then look at the errors reported by the browser. (mine is a Safari browser and I looked at the error with "Develop -> Show Javascript Console".

**Expected behavior**
If it recognized the "Script" node, it would turn the lamp on or off if you click on it. The error message of course explains why this doesn't happen: it doesn't recognize a "Script" node.

I also attached lampposterror.png, showing what I see when I open the file. You can see the lamppost on the X3DCanvas. But look at the error log below.

This is Mac OS Mohave 10.14
Safari Version 12

I downloaded other examples from the create3000.de website which included Script nodes (such as the FlashingLights example), and they work fine. But I don't know if I needed an extra command in the file header to make it recognize the Script node itself, or if Script nodes can only be used inside certain grouping nodes such as <Layer> or <ProtoBody>. I also tried temporarily deleting the "component" commands in the <head> section to see if that made a difference in the FlashingLights. But it didn't. It still worked.

Maybe you can see in my lamppostxi file why the Script node isn't recognized where it is located. By the way, it works in Instant Player. Thanks.

<img width="1225" alt="lampposterror" src="https://user-images.githubusercontent.com/52983707/62654260-40d9a280-b914-11e9-8d78-a931e0e37290.png">

[lamppostxi.txt](https://github.com/create3000/x_ite/files/3478639/lamppostxi.txt)

**Comment by splace** [comment]
you asked for the 'Interchange' profile, so no scripting allowed.

```
<X3D profile="Interchange" version="3.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"

```

try 'Immersive'

please close after confirming this is it.

**Comment by billy-castle** [comment]
Thank you for this information. I actually did look and found two differences from the header I’ve been using (a creation of the view3dscene code converter by the way), which are the InterChange profile you mentioned and the version 3.0. I changed them to Immerse and 3.3, as seen in the create3000 fileheaders. Now my script have started working. Thanks.

Billy Gard
duckfeetbilly@gmail.com
