### ISSUE TITLE
x_ite_dom 1.3 release

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#51]
I released a new version of x_ite_dom fixing an issue introduced by changes to the x_ite parser where parser.nodeAttribute now only deals with initializeOnly fields. Could you please change references on the web page to the latest version ?
https://raw.githack.com/andreasplesch/x_ite_dom/master/release/x_ite_dom.1.3.js
Thanks

**Comment by jamesleesaunders** [comment]
Would it not be more appropriate to directly link to the ‘latest’ path:
https://raw.githack.com/andreasplesch/x_ite_dom/master/latest/x_ite_dom.js
Then you don’t need to worry about updating the website every time?

**Comment by andreasplesch** [comment]
I will keep providing both, manually.

**Comment by create3000** [comment]
Updated references :-).

**Comment by andreasplesch** [comment]
Thanks.!
