### ISSUE TITLE
browser.replaceWorld ignores new Viewpoints ?

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#52]
x_ite_dom uses the SAI .replaceWorld method but it does not seem to pickup new Viewpoints in Inlines:
http://andreasplesch.github.io/Library/Examples/html5/PopGlobe/index_xite.html
I see if I can produce a minimal test example.

**Comment by andreasplesch** [comment]
I think is was just a matter of adding a `description` field. With it, the Inline viewpoint shows up but still is not used by default even it is the only viewpoint. Without it, the inline viewpoint is loaded but cannot be accessed, even with the PgUp/Dn keys.

**Comment by create3000** [comment]
There is a browser option _EnableInlineViewpoints_ https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/networking.html#BrowserProperties. Call `Browser.setBrowserOption("EnableInlineViewpoints", true);`.

**Comment by create3000** [comment]
EnableInlineViewpoints is by default **false**, when enabled then Viewpoints will be searched also in Inline nodes.

**Comment by andreasplesch** [comment]
The table 9.2 https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/networking.html#BrowserProperties says  the default should be _True_ as far as I can tell ?

**Comment by create3000** [comment]
See also https://github.com/create3000/titania/issues/56

**Comment by create3000** [comment]
I see now it is **true**. But I think for VRML2.0 scene it should be false. See referenced issue.

**Comment by create3000** [comment]
Additionally, Viewpoint node are only in the ContextMenu -> Viewpoints if they have a description.

**Comment by andreasplesch** [comment]
Ok, according to

http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/core.html#BindableChildrenNodes

Inline Viewpoints cannot be used as the first bound Viewpoint, in any situation.

**Comment by splace** [comment]
@create3000 

just wondering... might this enable the ability to render from inline/externProto viewpoints in Titania?
