### ISSUE TITLE
browser .supportedProfiles removed ?

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#53]
The browser object is supposed to have a supportedProfiles array:

https://www.web3d.org/documents/specifications/19777-1/V3.3/Part1/functions.html#t-PropertiesOfTheBrowserObject

and I think x_ite used to have it. Is it removed now ?

It looks like now browser.getProfile('name') is the way to find a profile.

**Comment by andreasplesch** [comment]
yeah, brower.getProfile('Immersive') works as an argument to set a scene's profile. But I think the standard prefers the supportedProfiles array although it is more cumbersome to use.

**Comment by create3000** [comment]
Is indeed missing. Have fixed that.

**Comment by create3000** [comment]
X3DInfoArray values can be accessed both by indices and property names, ie. you could use `Browser.supportedProfiles[0]` and `Browser.supportedProfiles['Full']` to get a profile. This is similar to `document.forms` in HTML.

**Comment by create3000** [comment]
May be the second version should be allowed by the spec.

**Comment by andreasplesch** [comment]
Yes, the second version using the name as the index would be more convenient. But I doubt that such a data type exists in the abstract SAI spec.

Thanks.
