### ISSUE TITLE
Duplicate retrievals from dynamically created Inline node

### ISSUE THREAD

**Issue by Sgeo** [create3000/x_ite#54]
**Describe the bug**
When I try to dynamically create an Inline node, I see two network requests for the same asset. I expect to see one.

(I'm uncertain if this is related to another issue I'm having where a quickly dynamically generated Import is sometimes usable and sometimes not.)

**To Reproduce**
The below is a part of the code I'm using. I can write a full test case later if needed

```javascript
    function addSO(browser, obj) {
        let inline = browser.currentScene.createNode("Inline");
        inline.url = new X3D.MFString(obj.url);
        browser.currentScene.addRootNode(inline);
    }
```

**Additional context**

**Comment by create3000** [comment]
Tanks. I confirm this bug. This happens to all X3DUrlObjects.
