### ISSUE TITLE
new PointProperties fields missing in HTML support

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#56]
**Describe the bug**
The new PointProperties node has fields which are not supported as DOM attributes.

**To Reproduce**
https://raw.githack.com/jamesleesaunders/d3-x3d/ScatterPlot/examples/X_ITE/chart/ParticlePlot.html

**Expected behavior**
Points should be larger

fix by 

```js
define ('x_ite/Parser/HTMLSupport',[],function ()
{
"use strict";

	var HTMLSupport =
	{
		attributeLowerCaseToCamelCase:
		{
			"pointsizeminvalue" : "pointSizeMinValue",
			"pointsizemaxvalue" : "pointSizeMaxValue",
			"pointsizescalefactor" : "pointSizeScaleFactor",
			"pointsizeattenuation" : "pointSizeAttenuation",					
			"accesstype" : "accessType",
...
```

**Comment by andreasplesch** [comment]
see PR #57

**Comment by create3000** [comment]
Also added Annotation component, ProjectiveTextureMapping component, and HAnimMotion.
