### ISSUE TITLE
dom integration partially broken

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#58]
https://github.com/create3000/x_ite/commit/95c12e6584ca0a8a88168f4649abeb5ab241de94

somehow broke DOM integration, see https://github.com/andreasplesch/x_ite_dom/issues/35

Any hints what could have happened, or how to fix ?

Here is a non-working example:

https://andreasplesch.github.io/x_ite_dom/tests/jqueryui_adopt.xhtml

**Comment by create3000** [comment]
Had renamed Parser.attributeToCamelCase, but this is used by X_ITE_DOM. Fixed that and released a new version 4.6.10. It could take a while (maybe days) until rawgit is up to date, due to caching. Thank you.

**Comment by andreasplesch** [comment]
Thanks. I think this was it. For githack (rawgit is not updated anymore), it is possible to use the commit hash directly to force it to use that version without caching:
https://rawcdn.githack.com/create3000/x_ite/f179017bc5ddd17ab159eb6f54d7681be0564507/dist/x_ite.js

**Comment by andreasplesch** [comment]
If you prefer 'fieldToCamelCase', I can of  course update x_ite_dom. But I think 'attribute' may be more accurate since it is about the xml attribute name, not the x3d field name.

**Comment by create3000** [comment]
I think it is fine as it is. I commented the function that it is used by x_ite_dom. Stay healthy.

**Comment by andreasplesch** [comment]
ok, thanks.
