### ISSUE TITLE
a few duplicated methods

### ISSUE THREAD

**Issue by andreasplesch** [create3000/x_ite#59]
lgtm.com found a few duplicated methods:

https://github.com/create3000/x_ite/blob/master/src/x_ite/Components/VolumeRendering/X3DVolumeDataNode.js : initialize

https://github.com/create3000/x_ite/blob/master/src/x_ite/Components/Texturing/TextureCoordinateGenerator.js : getTexCoord

**Comment by create3000** [comment]
Fixed.
