### ISSUE TITLE
Failed to laod

### ISSUE THREAD

**Issue by softscan** [create3000/x_ite#61]
Using your example file as a template with x_ite.zip in the root. Zipprd fo;der uploaded here
[files.zip](https://github.com/create3000/x_ite/files/4776997/files.zip)
Your example loads fine. Mine with my x3d gives the error
This happens with all my existing cobweb pages viewed offline in chrome and firefox which are latest versions

**Comment by create3000** [comment]
Close this because it should be because of CORS reason when loading locally from file: protocol. A http://localhost server should be used.
