### ISSUE TITLE
error attempting to duplicate load resource file from proto location

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#65]
seems to be when resource is used by proto located in sub-folder, but not always, resource is ALSO loaded correctly so this makes no visual difference.

new and old versions of x-ite / different browsers / + titania.

example: https://splace.github.io/3d/2003/blocks/blockTests.wrl

![Screenshot from 2020-08-31 18:19:46](https://user-images.githubusercontent.com/1234848/91747921-fb3ee600-ebb6-11ea-863b-861e7ef1862e.png)

**Comment by create3000** [comment]
Sorry for the late response. Resources like images which are defined in a proto are loaded as often as a proto instance is defined, caching is done by the browser.

**Comment by splace** [comment]
so why error?
