### ISSUE TITLE
Suggestion idea: shared events

### ISSUE THREAD

**Issue by jordircardona** [create3000/x_ite#66]
This is an idea. I have put my old vrml worlds again online, thanks to x_ite (a big thank you!). It is fantastic to finally accomplish what VRML was supposed to do: standard 3d on the web without plugins. I also put a review in my blog and tutorials in my blog, personal page and facebook groups about x_ite.
This is the url for my worlds, that have sound, javascript and everything, and all works fine on x_ite: http://hipercubo.atwebpages.com/Mundos-VRML
If you need the source files I can send them to you for testing.
The other point, never done, is to have plugin-less multiuser 3d spaces: chat & shared events. Everybody is asking for it everywhere in x3d and vrml communities
I wonder if there is some plan to add this through for example this: https://temasys.github.io/how-to/2014/09/02/Building_A_Simple_P2P_chat_with_WebRTC/
or this:
https://github.com/jalmasi/vrspace
Just an idea, I know it is out of the scope.Again, thanks a lot for this.

**Comment by jalmasi** [comment]
Hi,
main point of integration with vrspace server would be https://github.com/jalmasi/vrspace/blob/master/babylon/vrspace.js

**Comment by create3000** [comment]
There is an addFieldCallback function on SFNode objects: https://github.com/create3000/x_ite/wiki/Field-Services-and-Objects#void-addfieldcallback-name-key-callback. You can there connect to an field and catch all event occurred.

**Comment by binoclard2005** [comment]
good idea, 
but, backgroun not work, the world come poor :)
hi jordi :)
