### ISSUE TITLE
Minor Bug or Feature. Cursor mapping in div with padding.

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#67]
Hi,

I was working on https://satadorus.eu/x_ite/yacs_2_0/yacs_2_0.html when I noticed a problem with the cursor mapping of a touchSensor...

NOTE: In the above file the issue is fixed already!

In the Y-direction the mouse cursor was a few pixels off.
I wrote a test file and the problem was gone...
I then added a test shape to my world: same problem.
I removed most VRML code: same problem.

After a while, I figured out that I (maybe a copy-paste error) added **padding: 8pix;** to the **div** that contained the X_ITE browser window.

I checked that:

1) padding doesn't do anything: you can still move the 3D scene all the way to the border.
2) padding does change the width of the division just as it does for divisions containing text.
3) padding does however change the cursor mapping of a touchSensor in the Y-direction:
- The cursor turns to the hand symbol only when 8 pix inside the shape associated with the sensor, and above it it is possible to touch just outside the shape.

The pictures show what happens if you move the mouse cursor in, over, and then out of the shape from bottom to top,

![capture_001](https://user-images.githubusercontent.com/6066508/106296208-aa104c80-6251-11eb-8f2d-2fbdef8bf357.png)
![capture_002](https://user-images.githubusercontent.com/6066508/106296211-aa104c80-6251-11eb-8f85-1f11ab179cdb.png)
![capture_003](https://user-images.githubusercontent.com/6066508/106296213-aaa8e300-6251-11eb-802a-2d9715d41856.png)
![capture_004](https://user-images.githubusercontent.com/6066508/106296214-aaa8e300-6251-11eb-8fac-8d6db1772703.png)
![capture_005](https://user-images.githubusercontent.com/6066508/106296216-aaa8e300-6251-11eb-98fb-847e1b872a39.png)

Thanks,

Olaf

**Comment by create3000** [comment]
Thank you for reporting this bug, I could fix it.

**Comment by olafgithub** [comment]
Hello Holger,

Thanks!

I did a quick fix by just changing the CSS

Best regards from boring Eindhoven,

Olaf

________________________________
Van: Holger Seelig ***@***.***>
Verzonden: dinsdag 13 april 2021 12:19
Aan: create3000/x_ite ***@***.***>
CC: olafgithub ***@***.***>; Author ***@***.***>
Onderwerp: Re: [create3000/x_ite] Minor Bug or Feature. Cursor mapping in div with padding. (#67)


Thank you for reporting this bug, I could fix it.
