### ISSUE TITLE
"TypeError: e.copy is not a function" for loadURL

### ISSUE THREAD

**Issue by rafael-alcantara** [create3000/x_ite#69]
**Describe the bug**
When I use the Browser.loadURL function, I get this "TypeError: e.copy is not a function"

**To Reproduce**
1. Load an test.html file from localhost (HTTP protocol). The file includes an X3DCanvas element, with or without a working src attribute (I use "test.x3d", a sibling to the test.html file, with just a box and it is loaded ok).
2. Click a button on the page which triggers this test function)
```javascript
function test(){
    X3D.getBrowser().loadURL('test.x3d');
}
```
3. Get the error _"TypeError: e.copy is not a function"_ and this stack:
```
loadDocument (https://create3000.github.io/code/x_ite/4.6.11/dist/x_ite.min.js#20)
createX3DFromURL (https://create3000.github.io/code/x_ite/4.6.11/dist/x_ite.min.js#20)
loadURL (https://create3000.github.io/code/x_ite/4.6.11/dist/x_ite.min.js#43)
test (http://localhost:8080/board/test.html#9)
onload (http://localhost:8080/board/test.html#12)
<anonymous> (http://localhost:8080/board/test.html#11)
```
4. The value of e is the String "test.x3d".
5. Similar result if I use an absolute URL "http://localhost:8080/board/test.x3d" instead of the relative one, or if I wrap the URL in an array.

**Expected behavior**
Load the x3d file in the browser.

**Desktop (please complete the following information):**
 - OS: xubuntu linux 20.04 (64 bit)
 - Browser Firefox 86.0.1 (64 bit
 - X_ITE 4.6.11

**Comment by create3000** [comment]
Please not that the arguments for loadURL are MFString's:
`loadURL(url:MFString, parameter:MFString)`
This means you should call `X3D.getBrowser().loadURL(new X3D.MFString('file.x3d'), new X3D.MFString())`

See also https://github.com/create3000/x_ite/wiki/Browser-Services#methods.
