### ISSUE TITLE
[info] very high frame rate causing freeze/lockup

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#71]
*only for info since may be browser/os thing*

**To Reproduce**
load world in browser without FPS limit (linux command-line prefix: 'vblank_mode=0' )
zoom/look so no/little geometry on screen causing FPS to go v. high

**Desktop (please complete the following information):**
 - Solus
 - Epiphany 3.34 pretty new

![Screenshot at 2021-04-07 22-29-46](https://user-images.githubusercontent.com/1234848/114623809-ad8b6f80-9ca7-11eb-9d16-a58169261d0a.png)

**Comment by create3000** [comment]
Think it mentioned somewhere that you should not do that (vblank_mode=0).

**Comment by splace** [comment]
reported, as info, because i wondered if it might occur on high refresh rate monitors?
