### ISSUE TITLE
Supporting CORS in X3D-Edit via Java to support X_ITE presentation of X3D models

### ISSUE THREAD

**Issue by brutzman** [create3000/x_ite#72]
Now that X3D-Edit 4.0 is running (in beta) again, am looking for a simple way to add a CORS option using Java so that authors can use X_ITE on locally converted models. Hopefully this can be done on localhost for a variety of Web browsers, so that authors have maximum ability to test X_ITE presentation of X3D models.
[https://savage.nps.edu/X3D-Edit](https://savage.nps.edu/X3D-Edit)
![image](https://user-images.githubusercontent.com/7712992/118383697-30f4f500-b5b5-11eb-99ce-5adc5436335f.png)

_Originally posted by @brutzman in https://github.com/create3000/x_ite/issues/22#issuecomment-841756638_

**Comment by create3000** [comment]
X_ITE should run fine on a localhost server. Yes, this is the only way to test scenes. There are various programs on the Internet that provide a localhost server, also some are very easy to use. https://github.com/create3000/x_ite/wiki#using-firefox-chrome-and-opera-with-local-files
