### ISSUE TITLE
Little white flashing flower appearing in middle of sphere.

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#74]
**Describe the bug**
Once the motion begins, a little white flashing flower? appears in the middle of the sphere.

**To Reproduce**
1. Go to https://coderextreme.net/X3DJSONLD/src/main/html/bubbles.html

**Expected behavior**
No flashing flower. Empty sphere

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Groovy Gorilla 20.10
 - Browser Chromium, Firefox
 - Version latest X_ITE

**Comment by coderextreme** [comment]
First load after cache works.  On second load, white flower comes back.   Tried commenting out x3dom shader (x3dom doesn't do VRML scripts anyway).

**Comment by create3000** [comment]
Tested on Firefox and Safari on macOS and it works well. Can only be some kind of caching the browser does. There are 'Clear Cache' extensions for Firefox and Chrome, have you tried this?

**Comment by create3000** [comment]
See #46 at the end for Firefox and Chrome links.

**Comment by coderextreme** [comment]
Clearing cache with extension for Chromium mentioned in #46 did not work.  There must be some other kind of caching going on?  Caching of shaders?   I don't know if this scene ever had flowers.   Maybe it's some kind of glitch?

**Comment by create3000** [comment]
![Bildschirmfoto 2021-07-05 um 22 00 26](https://user-images.githubusercontent.com/2930196/124514109-98bd0480-dddc-11eb-9148-636423d6366f.png)

There is no flower, only one bubble.

**Comment by coderextreme** [comment]
The white structure looks like a square with 2 opposite corners cut off, right in the the middle of the sphere, flashing.  I  see your picture.  It seems like in some cases, the flashing begins at the end or beginning of a camera animation leg (as in journey--a key frame?).  I have a pretty good idea what it looks like.  I have been using chrome with the extension for clearing cache.

I'm going to say it's some kind of reflection of the sky, I guess.

Could it be a driver or linux GUI issue? I have a GTX 980

It doesn't show for most of the time. but the flashing does make it very obvious.

I've removed all the x3dom code, since the script is not suitable for X3DOM as it is, so it's not a shader loading issue.

**Comment by coderextreme** [comment]
The flashing appears when the camera is level the most I think.  I wish I could be more help! Maybe we could hook up on Discord and I can share my screen? I am yottzumm#9156.

**Comment by splace** [comment]
i get it, firefox r7-250, non-NVIDIA shader maths? rounding?

starts about 10s in

https://user-images.githubusercontent.com/1234848/124517841-f05b7000-dddc-11eb-957a-48e720295c8f.mp4

**Comment by coderextreme** [comment]
The non-issue may be easier to see on iOS with safari or chrome.   There’s a big white light spot facing the camera on a nearly opaque sphere.   Perhaps some transparency or reflection on the backside of the sphere.  My guess is different issues come with differently capable graphics card.   Does iOS support WebGL2?   Apparently it’s an experimental feature.   I guess I’ll stick to desktop.

**Comment by coderextreme** [comment]
I will try to capture video.  I am a Linux noob.   But I am with family now.

**Comment by coderextreme** [comment]
@splace, yes, that captures it nicely.   I think it may be due to the lighting coming from the Viewpoint, not really sure.

**Comment by coderextreme** [comment]
I get the problem on NVidia GTX 980.   It may just be a lightning thing?
Not really sure at this point, we probably need more data points.

**Comment by coderextreme** [comment]
![CEE75287-3581-436A-AB01-DFA981B862F5](https://user-images.githubusercontent.com/705783/124518583-6a273580-ddac-11eb-9351-2addfea484a2.png)

**Comment by create3000** [comment]
On Samsung tablet there is also this artifact.

**Comment by create3000** [comment]
I think, I got it. The problem comes from the `rfac` variable, it was in the wrong range. I fixed that by doing some clamp, and normalized fragNormal. By doing debug, I also beautified your shaders a bit, think so. Instead of using mpv, you can use x3d_NormalMatrix, think that is what you mean. At the end of the shader you can use a build-in`mix`,which should be faster. And removed `cube` user-defined field from ComposedShader.

Here is the new [bubbles.zip](https://github.com/create3000/x_ite/files/6769878/bubbles.zip)
