### ISSUE TITLE
get KhronosGroup glTF-Sample-Models 2.0 IridescentDishWithOlives working

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#76]
**Describe the bug**
Get this example using KHR extensions to glTF 2.0 working:

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/IridescentDishWithOlives

**To Reproduce**
Check out web site and see example images and animation

**Expected behavior**
Something that will pass glTF conformance, if any.

**Screenshots**
See link

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - Browser Chrome, Firefox
 - Version (probably WebGL2 support)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 plus
 - OS: iOS 14.7
 - Browser Chrome, Safari
 - Version (recent)
**Additional context**

**Comment by create3000** [comment]
This feature is be implemented in the next release. I will provide further informations on x3d-public if I release this feature. 😊

**Comment by create3000** [comment]
Have added a preview image above.

**Comment by create3000** [comment]
Closing now because implemented. :)
