### ISSUE TITLE
Browser is updating the web address to include src.

### ISSUE THREAD

**Issue by dburleson** [create3000/x_ite#77]
**Describe the bug**
I'm trying to integrate the x3d browser into a vuejs project. I've included the css and js file and have confirmed it's reloading. However, when I try to load a .wrl file, it appends the file's address to the web address of the page. This is when using the setAttribute('src') method. When I try to use loadURL(), I get an undefined.

**Expected behavior**
I would expect the x3d browser to load the wrl file without updating the web address of the webpage.

**Comment by create3000** [comment]
What web browser do you use? Is the file's url appended in the _location bar_ of the web browser? 

The behavior is that if you specify an relative url then this url is resolved against the base url of the web page or current document.

The use of loadURL could maybe wrong, correct usage is Browser.loadURL(new MFString ("your/world.x3d"), new MFString ()), see also https://github.com/create3000/x_ite/wiki/Browser-Services#void-loadurl-mfstring-url-mfstring-parameter.

**Comment by dburleson** [comment]
> What web browser do you use?

Latest Google Chrome  95.0.4638.69

> Is the file's url appended in the location bar of the web browser?

Yes

> The behavior is that if you specify an relative url then this url is resolved against the base url of the web page or current document.

Then I need to include the absolute web url to load a .wrl file then? Even if it's on the exact same server?

> The use of loadURL could maybe wrong, correct usage is Browser.loadURL(new MFString ("your/world.x3d"), new MFString ()), see also https://github.com/create3000/x_ite/wiki/Browser-Services#void-loadurl-mfstring-url-mfstring-parameter.

Thanks for the heads up, that has solved that error. But now i'm getting this error:

```
vue.runtime.esm.js?2b0e:1897 TypeError: t.addParent is not a function
    at Proxy.set (x_ite.min.js:9)
    at Proxy.setValue (x_ite.min.js:6)
    at y.push (x_ite.min.js:9)
    at y.s [as constructor] (x_ite.min.js:9)
    at new y (x_ite.min.js:9)
    at VueComponent.loadWorld (HomePage.vue?f990:50)
    ```
