### ISSUE TITLE
How to remove/destroy an x_ite/X3D instance in JavaScript?

### ISSUE THREAD

**Issue by dburleson** [create3000/x_ite#78]
I'm integrating x_ite browser into a javascript SPA. I need to know if there is a specific way to remove/destroy the x3d/x_ite browser instance. What is the best method to remove it?

**Comment by create3000** [comment]
In JavaScript it is not really possible and actually also not needed to delete an object, as JavaScript has garbage collection inside, but this is very lazy of course :(. 

What you can do is to call `Browser.replaceWorld(null)` to set an empty scene, this will disable event execution in the old scene.

**Comment by dburleson** [comment]
Might this also remove the x_ite browser's resources from hanging around in the background?

**Comment by dburleson** [comment]
I've tried this and it doesn't really solve the problem.

When X3D() is first called, a number of scripts are injected into the dom's HEAD and I imagine some start scripts are also ran. 

Ideally there should be a way to unload or easily destroy/remove the entire X3D() instance to avoid it hanging around in the browser's memory/resources.

**Comment by create3000** [comment]
With latest version, script injection is past.

**Comment by create3000** [comment]
Does the problem still persist. Otherwise I would close this issue.
