### ISSUE TITLE
Cannot read properties of undefined (reading 'setGlobalVariables') infinite loop

### ISSUE THREAD

**Issue by dburleson** [create3000/x_ite#79]
https://github.com/create3000/x_ite/blob/b9b32e964553d5e79b953db01d02d6c2e72d1f8e/src/x_ite/Rendering/X3DRenderObject.js#L942

Using a JavaScript SPA (Vue), I initially visit a page which loads a world fine. However, after visiting a new page in the SPA, which removes the element and re-visiting, I get an infinite loop of:
```
Cannot read properties of undefined (reading 'setGlobalVariables')
```

The code I'm running is:

```
X3D(() => {
                    console.log('x3d started...');

                    console.log('creating browser...');
                    this.browser = X3D.createBrowser();
                    console.log('attaching browser...');
                    document.querySelector('#world').appendChild(this.browser);
                    console.log('getting and loading world...');
                    X3D.getBrowser('X3DCanvas').loadURL(new X3D.MFString(this.worldURL), new X3D.MFString());


                },
                (error) => {
                    console.error('error dave!');
                    console.error(error);

                });
```

I `delete this.browser` in a attempt to resolve this issue, which doesn't rectify the problem.

**Comment by create3000** [comment]
It seems that you are using an old browser instance maybe? Is the init callback, as seen above, where you create the X3DCanvas element again called when you re-visit the page?

Have you tried X3D.getBrowser(this.browser)?

**Comment by dburleson** [comment]
> It seems that you are using an old browser instance maybe?

This is what it appears to be causing the issue. And this is why I was asking about how to remove/destroy a browser instance. VueJS revomes the DOM element, but I suspect the browser is still in the browser resources.

When a url is changed, keeping in mind this is javascript, not true page reloads, VueJS checks for differences in the DOM and pushes it all up to the browser. It also unloads old resources used by the vue js component/page. However, I think X3D/x_ite is hanging onto the resources and when I go back to the re-load the component, the browser instance is still in memory somehow and causing this infinate loop.

**Comment by create3000** [comment]
I have looked at vue.js and it looks very simple and easy to use, but I do not have any idea what you are doing causing the errors. Can you provide a minimal example page, triggering the error.

**Comment by create3000** [comment]
Here is an article to JavaScript garbage collection: https://javascript.info/garbage-collection
