### ISSUE TITLE
Wrong behavior of TransformSensor position_changed output field

### ISSUE THREAD

**Issue by fkievith** [create3000/x_ite#80]
**Describe the bug**
The TransformSensor position_changed output seems to give wrong output values.

**To Reproduce**
Render [TransformSensor-issue.x3d.gz](https://github.com/create3000/x_ite/files/7511564/TransformSensor-issue.x3d.gz) with X_ITE X3D Browser 4.6.23.

**Expected behavior**
The rendered coordinate axes on the 2nd layer of the scene shall be aligned to the origin of the shapes during the animation.

**Console log from web browser**
Welcome to X_ITE X3D Browser 4.6.23:
   Current Graphics Renderer
      Name: Google Inc. (Intel) ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.100.9664)
      WebGL version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
      Shading language: WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
   Rendering Properties
      Antialiased: true
      Depth size: 24 bits
      Color depth: 32 bits
      Max clip planes: 6
      Max global lights: 4
      Max textures: 2
      Texture units: 32
      Max texture size: 16384 × 16384 pixel
      Texture memory: NaN
      Max vertex uniform vectors: 4096
      Max fragment uniform vectors: 1024
      Max vertex attribs: 16

x_ite.min.js:18 Couldn't initialize ComposedShader 'GouraudShader': C:\fakepath(424,1): warning X4000: use of potentially uninitialized variable (f_getTexCoord)
C:\fakepath(578,1): warning X4000: use of potentially uninitialized variable (f_getTexture2DLod0)
C:\fakepath(606,1): warning X4000: use of potentially uninitialized variable (f_getTexture3DLod0)
C:\fakepath(634,1): warning X4000: use of potentially uninitialized variable (f_getTextureCubeLod0)
C:\fakepath(424,1): warning X4000: use of potentially uninitialized variable (f_getTexCoord)
C:\fakepath(578,1): warning X4000: use of potentially uninitialized variable (f_getTexture2DLod0)
C:\fakepath(606,1): warning X4000: use of potentially uninitialized variable (f_getTexture3DLod0)
C:\fakepath(634,1): warning X4000: use of potentially uninitialized variable (f_getTextureCubeLod0)
C:\fakepath(424,1): warning X4000: use of potentially uninitialized variable (f_getTexCoord)
C:\fakepath(578,1): warning X4000: use of potentially uninitialized variable (f_getTexture2DLod0)
C:\fakepath(606,1): warning X4000: use of potentially uninitialized variable (f_getTexture3DLod0)
C:\fakepath(634,1): warning X4000: use of potentially uninitialized variable (f_getTextureCubeLod0)
C:\fakepath(937,1): warning X4000: use of potentially uninitialized variable (f_getProjectiveTextureLod0)
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Negate modifier not allowed for operand #5 of opcode #52 (counts are 1-based). 
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Negate modifier not allowed for operand #5 of opcode #67 (counts are 1-based). 

Warning: D3D shader compilation failed with default flags. (ps_5_0)
 Retrying with skip validation
C:\fakepath(424,1): warning X4000: use of potentially uninitialized variable (f_getTexCoord)
C:\fakepath(578,1): warning X4000: use of potentially uninitialized variable (f_getTexture2DLod0)
C:\fakepath(606,1): warning X4000: use of potentially uninitialized variable (f_getTexture3DLod0)
C:\fakepath(634,1): warning X4000: use of potentially uninitialized variable (f_getTextureCubeLod0)
C:\fakepath(424,1): warning X4000: use of potentially uninitialized variable (f_getTexCoord)
C:\fakepath(578,1): warning X4000: use of potentially uninitialized variable (f_getTexture2DLod0)
C:\fakepath(606,1): warning X4000: use of potentially uninitialized variable (f_getTexture3DLod0)
C:\fakepath(634,1): warning X4000: use of potentially uninitialized variable (f_getTextureCubeLod0)
C:\fakepath(424,1): warning X4000: use of potentially uninitialized variable (f_getTexCoord)
C:\fakepath(578,1): warning X4000: use of potentially uninitialized variable (f_getTexture2DLod0)
C:\fakepath(606,1): warning X4000: use of potentially uninitialized variable (f_getTexture3DLod0)
C:\fakepath(634,1): warning X4000: use of potentially uninitialized variable (f_getTextureCubeLod0)
C:\fakepath(937,1): warning X4000: use of potentially uninitialized variable (f_getProjectiveTextureLod0)
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Negate modifier not allowed for operand #5 of opcode #52 (counts are 1-based). 
error X8000: D3D11 Internal Compiler Error: Invalid Bytecode: Negate modifier not allowed for operand #5 of opcode #67 (counts are 1-based). 

Warning: D3D shader compilation failed with skip validation flags. (ps_5_0)
 Retrying with skip optimization
C:\fakepath(640,7-53): error X3531: can't unroll loops marked with loop attribute

C:\fakepath(640,7-53): error X3511: forced to unroll loop, but unrolling failed.

Warning: D3D shader compilation failed with skip optimization flags. (ps_5_0)

Failed to create D3D Shaders

x_ite.min.js:21 X_ITE: All else fails, using fallback VRML shader.

**Comment by fkievith** [comment]
That was not obvious to me by reading the [specification about the TransformSensor](https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/envsensor.html#TransformSensor). I assumed it would track the orientation and position of the origin of the local coordinate space of the targetObject. Reading it again it is still not clear to me it tracks the bounding box of the targetObject. How does it work then? Should the targetObject's center of it's bounding box be inside the sensor box before isActive becomes true or if only some edge of the bounding box enters the sensor box?

My goal is not to track the center of the shape(s) but to track the local coordinate space of the targetObject. I tried it now by creating an empty group node (\<Group DEF='...' bboxSize='0 0 0' /\>) as targetObject in the local coordinate space I want to track, but that doesn't work either. An [_X3DBoundedObject_](https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/group.html#X3DBoundedObject) from which the Group node is derived allows a bboxSize='0 0 0', which is then regarded a point in space. Could you provide some clarifications or hints here?

**Comment by create3000** [comment]
Should be fixed now.

**Comment by fkievith** [comment]
Thanks! Awesome. It works now. Is this the implementation how the specification describes it?
