### ISSUE TITLE
Request for implementation of 'visible' field on X3DBoundedObject as specified by X3Dv4

### ISSUE THREAD

**Issue by fkievith** [create3000/x_ite#81]
I don't know if there is an implementation plan for x_ite to support X3D version 4 features, but I would really like the support of the 'visible' field as specified for the [X3DBoundedObject](https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/grouping.html#X3DBoundedObject) in X3Dv4.

**Comment by create3000** [comment]
There is no strict plan for implementing X3Dv4, but sure there are already thing done like PointProperties node and ProjectiveTextureMapping component. The main thing is that things can/will still change, and some thing are very time-consuming. But think 'visible' is very stable already.

**Comment by create3000** [comment]
In the last week I have implemented the new X3Dv4 fields _visible_, and _bboxDisplay_ of X3DBoundingBox. Beside this there are now the new X3Dv4 fields _alphaMode_, and _alphaCutoff_ of Appearance, and _castShadow_ of X3DShapeNode. I have released an alpha version of X_ITE, which is available at: https://create3000.github.io/code/x_ite/alpha/.

**Comment by fkievith** [comment]
It works great, thank you! 

You implemented even more. This _bboxDisplay_ field is also very handy to highlight a selected the hierarchy. This visible bounding box is always axis aligned with the world coordinate system of the X3D browser isn't it?

**Comment by create3000** [comment]
The bbox is axis aligned within the local coordinate system, but affected from the transformation hierarchy. This is what makes most sense and is visually descriptive. Other implementations do not make much sense.
