### ISSUE TITLE
OrthoViewpoint issues

### ISSUE THREAD

**Issue by fkievith** [create3000/x_ite#84]
**Describe the bug**
I have found some issues with the OrthoViewpoint node while using it in a scene with a LayerSet.

1. Switching to OrthoViewpoint produces an error in the webbrowser console.
2. retainUserOffsets field of OrthoViewpoint node is not respected.
3. Navigating the scene with the plane viewer and an OrthoViewpoint bound doesn't produce fieldOfView field change events and/or position change events to synchronize an OrthoViewpoint in another layer of the scene.

**To Reproduce**
1. Switching to OrthoViewpoint produces an error in the web browser console.
   1. Open [OrthoViewpoint-issue.x3d.zip](https://github.com/create3000/x_ite/files/7668856/OrthoViewpoint-issue.x3d.zip).
   2. Switch to Orthographic view (page up).
   3. Review web browser console.
2. retainUserOffsets field of OrthoViewpoint node is not respected.
   1. Open [OrthoViewpoint-issue.x3d.zip](https://github.com/create3000/x_ite/files/7668856/OrthoViewpoint-issue.x3d.zip).
   2. Switch to Orthographic view (page up).
   3. Do some navigation (like translating the view in the plane viewer).
   4. Switch to other viewpoint and back to Orthographic view.
   5. It jumps back to the position which was left before switching viewpoints instead of to position which is defined in OrthoViewpoint node.
3. Navigating the scene with the plane viewer and an OrthoViewpoint bound.
   1. Open [OrthoViewpoint-issue.x3d.zip](https://github.com/create3000/x_ite/files/7668856/OrthoViewpoint-issue.x3d.zip).
   2. Switch to Orthographic view (page up).
   3. Do some navigation while in plane viewer, like zooming in/out and translating the view.

**Expected behavior**
1. It shall not produce an error message.
2. It shall jump back to view defined in the OrthoViewpoint node when retainUserOffsets = FALSE.
3. OrthoViewpoint of the the 2nd layer shall be synchronized to OrthoViewpoint of 1st layer while a route is defined from fieldOfView of the OrthoViewpoint in the 1st layer to fieldOfView of OrthoViewpoint in the 2nd layer while doing navigation in the 1st layer.

**Desktop**
 - Browser: chrome
 - Version: 4.7.0
[Web browser console log](https://github.com/create3000/x_ite/files/7668890/localhost-1638886465305.log)

**Comment by create3000** [comment]
The fatal bug, which is now fixed in latest, has prevented the OrthoViewpoint from operating normally.

If you want the same viewpoint in a second layer, simply clone the viewpoint. To observe position, and orientation of a viewpoint use a ProximitySensor node.

**Comment by fkievith** [comment]
Thanks for the quick fix!

Points 1 and 2 are solved now. 
Regarding point 3 I did as you explained basically by setting the fieldOfView of the OrthoViewpoint in layer 2 identical to the one in layer 1. A ProximitySensor in layer 1 senses the viewer and updates the position and orientation of the OrthoViewpoint in layer 2 via a route. See [OrthoViewpoint-issue.x3d.zip](https://github.com/create3000/x_ite/files/7668856/OrthoViewpoint-issue.x3d.zip). However, while zooming in or out the layer 2 viewpoint isn't synchronized correctly to the one in layer 1.

**Comment by create3000** [comment]
It is not intended that the viewpoint sends events. The only way to get you example to work is to clone the viewpoint in booth layers.

**Comment by fkievith** [comment]
Great!  Exactly what I needed. That solution didn't came to my mind as I was under the impression a viewpoint can only be bound to one layer. Even the need for the _ProximitySensor_ is gone.

**Comment by fkievith** [comment]
I am reopening this issue as there is still one issue associated with OrthoViewpoint. The _jump_ field is by default `TRUE`, but when switching between OrthoViewpoints when plane viewer is selected it animates the transition instead of 'jumping'.

**Comment by create3000** [comment]
The _jump_ field means that the user will move or even jump to the position of this viewpoint. If NavigationInfo _transitionType_ field is "ANIMATE" than the transition will be animated, if you set _transitionType_ to "TELEPORT" than the transition will be instantaneous.

See https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/navigation.html#NavigationInfo.
