### ISSUE TITLE
geometry becomes distorted zooming out in 'plane' navigation

### ISSUE THREAD

**Issue by splace** [create3000/x_ite#85]
**Describe the bug**
see video

confirmed in webkit and gecko based browsers

https://user-images.githubusercontent.com/1234848/145656966-aa2c6e26-4eb5-4676-8151-19bcbd41c469.mp4

**Comment by create3000** [comment]
The PlaneViewer modifies the fieldOfView of the viewpoint node, when the fieldOfView becomes extreme, the scene can be somehow distorted. Although the PlaneViewer works with normal Viewpoint, it is mainly designed for use with **OrthoViewpoint**, where it works very well.

**Comment by splace** [comment]
OK

so, if i understand, the issue occurs because when using 'plane' navigation, and being at a non-orthoviewpoint, the UI lets you set a fieldofview over 180degrees?

**Comment by create3000** [comment]
No, the fieldOfView will never be more than π. Try changing fieldOfView and see what happens.

**Comment by create3000** [comment]
As PlaneViewer is designed to use with OrthoViewpoint node, I will close this issue now.
