### ISSUE TITLE
Unexpected navigation in FLY mode

### ISSUE THREAD

**Issue by giteck** [create3000/x_ite#86]
**Describe the bug**
Observations (for me they ere errors, except there are changes in the standard):

1. cannot move/fly backwards with the mouse (other viewers lice BS Contact and InstantReality behave as expected).
2. clicking, holding and moving the mouse forward (the cursor up!) not only moves, but introduces a direction-change upward; clicking, holding and moving the mouse backwards (mouse cursor down) continues moving forward, but changes the direction downward.
3. Trying to navigate with cursor keys seems to lead to stop/pause/freeze of the moving objects and the navigation does not work (happens after few key presses). No errors, context menu continues working, but it seems that the html browser is getting the focus (if there is space to scroll, the page starts scrolling) and the "scene clocks/timers" are stopped.
4. Not related to navigation: right-clicking near to the right-hand window edge opens the context menu properly, but no submenu can be seen, because they open out of the visible area. In this moment actually a horizontal scroll bar appears on the bottom of the window, but moving the mouse cursor towards it with the intention to scroll makes it disappear.

**To Reproduce**
1. Open, e.g. https://create3000.github.io/media/examples/X3D/LogoPieces/example.html
2. Try to change navigation to FLY and navigate forwards and backwards.
3. Try to press the arrow keys a couple of times (especially "up" and "down").
4. Right-clicking near to the right-hand window edge, try to choose any submenu. Watch for the horizontal scroll bar.

**Expected behavior**

1. Moving the mouse forward (mouse cursor up) or backward should not change the direction of the flight.
2. Moving backwards should move backwards.
3. Arrow keys offer an intuitive way to navigate within a scene and should work.
4. If there is not enough space for a submenu on the right-hand side, it should try to open on the left-hand side.

**Screenshots**
![image](https://user-images.githubusercontent.com/64155944/145727008-42dc8285-a6d4-4322-8b04-4bd60f654aac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 95.0 (64-bit); Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**Additional context**

**Comment by splace** [comment]
FYI being particularly interested in navigation UI, and having just tried (yesterday) x-ite on a touch screen, i found the behaviour very good and intuitive, multi-touch being particularly nice.

however for my large screen with a mouse with no middle button (but side scrolling) navigation is not so good.

given 'standard' expectations and available browser interfaces (i have been playing with controller) things are quite complicated. many years ago, i did a sort of paper on what i thought would be the ultimate 'best practice', but never got to the point of having feedback. (somethings i thought were better were non-standard currently, so acceptance not likely.)

**Comment by splace** [comment]
>> Arrow keys offer an intuitive way to navigate within a scene and should work.

seems very reasonable to me.

**Comment by create3000** [comment]
There is a KeySensor node in X3D, see https://www.web3d.org/documents/specifications/19775-1/V4.0/index.html, which sends events when a key is pressed. This enables X3D authors to implement their own navigation, or other behaviors. When a viewer would catch arrow keys events, then these keys would not be available for use for the X3D author.

**Comment by create3000** [comment]
All mentioned issues should have been fixed already. Closing this issue now.
