### ISSUE TITLE
How to access X3DExecutionContext of ProtoInstance or Inline nodes through external Browser SAI

### ISSUE THREAD

**Issue by fkievith** [create3000/x_ite#87]
I know how to access the execution context of the browser from Javascript by using the following code:
```javascript
const
    Browser      = X3D .getBrowser ("#browser"),  // X3DBrowser object
    currentScene = Browser .currentScene;          // X3DScene object
```
but once I have access to a ProtoInstance node like:
```javascript
const protoInstanceNode = currentScene .getNamedNode('DefNameOfProtoInstance');
```
or:
```javascript
const inlineNode = currentScene .getNamedNode('DefNameOfInlineNode');
```
I have no idea how to access the X3DExecutionContext of what those nodes contain. It seems to be a shortcoming of the [ISO/IEC CD 19777-1:201x](https://www.web3d.org/documents/specifications/19777-1/V3.3/index.html) specification as I find no reference to it. It only allows to access the X3DExecutionContext from a script node internal to the prototype or included scene it seems.
Do I overlook something or is it really not possible to access the X3DExecutionContext of ProtoInstance and Inline nodes from an external Browser?

**Comment by create3000** [comment]
There is a way to access these properties, but it is non standard and could change in future versions of X_ITE.

What you get from `getNamedNode` is a SFNode instance, this has the function getValue to get the underlying value, a X3DPrototypeInstance instance or an Inline instance. The X3DPrototypeInstance is also of type X3DExecutionContext and this is what you want. The Inline instance has a function `getInternalScene` and this is what you want, not that the scene is different after every load of the Inline.

```js
const
   protoInstanceNode = currentScene .getNamedNode('DefNameOfProtoInstance'),
   executionContext  = protoInstanceNode .getValue ();
```

```js
const
   inlineNode = currentScene .getNamedNode('DefNameOfInlineNode'),
   scene      = inlineNode .getValue () .getInternalScene ();
```

Note that these functions are special to X_ITE and can change in future versions of X_ITE.

**Comment by fkievith** [comment]
Thanks! This works for me now, but I hope at some point in the future there will be a standardized way described in the X3D SAI and it's language bindings.

**Comment by create3000** [comment]
I am actually in changing some internal structure a bit. I think that the access to the X3DPrototypeInstance execution context will be in the next version:

```js
const
   protoInstanceNode = currentScene .getNamedNode ('DefNameOfProtoInstance'),
   executionContext  = protoInstanceNode .getValue () .getBody ();
```

This is more secure and compatible with other languages.

**Comment by create3000** [comment]
Note the `getBody` call.
