### ISSUE TITLE
Physics and 2D - Possible?

### ISSUE THREAD

**Issue by anonimo82** [create3000/x_ite#88]
Hello everyone.
Is it possible to use Physics nodes with 2D geometries?
Something like Box2D.

Thanks in advance for any help.

**Comment by create3000** [comment]
No, RigidBodyPhysics nodes are specially designed for 3D objects. The are some other physics engines especially for 2D, for instance https://brm.io/matter-js/.

**Comment by anonimo82** [comment]
Can I use MatterJS with x3D?

**Comment by create3000** [comment]
This is what I don't now. But you could also use 3D Objects like Box, Sphere, and use a OrthoViewpoint to get a 2D look of the scene.

**Comment by anonimo82** [comment]
Ok, thanks anyhow.
Merry Christmas and a GREAT new year
