### ISSUE TITLE
Version 4.7.1 executes code in VRML Script node after loading

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#89]
**Describe the bug**

A few days ago I was demonstrating a few things to a visitor.
Some of my projects started up looking very weird. Like if someone had already pushed some buttons...

I used /latest/   that was 4.7.1
After some trial and error, I found that 4.7.0 was still fine.

Today I figured out what went wrong.
I reduced it to 2 files: A very simple HTML file that includes X_ITE and an almost empty VRML file with a single script.

When running the 4.7.0 version all is ok
When running the 4.7.1 version **the function in the script is called immediately after loading the page**. It prints a message on the console.

I attach the 3 files: HTML files for both versions and the .wrl VRML file.

**To Reproduce**

The test code is available on:

https://satadorus.eu/test_x_ite_bug/test_4_7_0.html
and
https://satadorus.eu/test_x_ite_bug/test_4_7_1.html

Look at the console to see the call to the function in the script/

**Desktop (please complete the following information):**
 - OS: Winsows 10
 - Chrome
 - Version Version 96.0.4664.110 (Official Build) (64-bit)

===================== content of the HTML file =========================

<!DOCTYPE html>
<html lang = "en" >

  <head>
    <meta charset="utf-8"/>

    <link rel="stylesheet" type="text/css" href="https://create3000.github.io/code/x_ite/4.7.1/dist/x_ite.css"/>
    <script type="text/javascript" src="https://create3000.github.io/code/x_ite/4.7.1/dist/x_ite.min.js"></script>

    <title>TEST DIFF BTW 4.7.0 and 4.7.1</title>
  </head>                                               

  <body>                                                                                                              

    <X3DCanvas id = "x3d_1"  
       src          =  "./test.wrl"  
       splashScreen = "true"     4           >

      <p>Your browser may not support all features required by X_ITE.
         For a better experience, keep your browser up to date.
         <a href="http://outdatedbrowser.com">Check here for latest versions.</a>
      </p>
    
    </X3DCanvas>
    
  </body>
</html>
     
===================== content of the VRML file test.wrl ====================

#VRML V2.0 utf8

Script
{
  eventIn   SFInt32   intval

  url "javascript:

    function intval( v )
    {
      console.log( '======================> function intval( ' + v + ' )' );                    
    }
  " 
}

**Comment by create3000** [comment]
Thank you. Have fixed this. Merry Xmas.

**Comment by olafgithub** [comment]
Wow that is fast... Are you on triple pay today :-)
Does it mean I can uses /latest/ again?

Thanks!

**Comment by create3000** [comment]
LOL. 'latest' is up to date again and you can use it.
