### ISSUE TITLE
Some shapes are not shown in version 4.7.1

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#90]
When testing with 4.7.1 I noticed that **some shapes are just not shown at all.**

Look at: https://satadorus.eu/x_ite/yacs_2_0/yacs_2_0.html (here you see the container. this is still version 4.7.0)

When I use 4.7.1 the container is not shown.
It uses JavaScript to generate a Circular Extrusion node with createVrmlFromString()

I reduced the code to the bare minimum:

https://satadorus.eu/test_x_ite_bug/container_bug/test_4_7_0.html (OK: shows the base of the container)
https://satadorus.eu/test_x_ite_bug/container_bug/test_4_7_1.html (BUG: nothing here)

I see very concise error messages on the console. 

Windows 10
Google Chrome: Version 96.0.4664.110 (Official Build) (64-bit)

Thanks,

Olaf

========================= example of error msg on console ========================

scripting.min.js:1 JavaScript Error in Script 'SCR', in function 'initialize'
world url is 'https://satadorus.eu/test_x_ite_bug/container_bug/test.wrl':
setError @ scripting.min.js:1
scripting.min.js:1 TypeError: Cannot convert object to primitive value
    at Object.initialize (eval at <anonymous> (create3000.github.io/code/x_ite/latest/dist/assets/components/scripting.min.js:1), <anonymous>:41:34)
    at C.set_live__ (create3000.github.io/code/x_ite/latest/dist/assets/components/scripting.min.js:1)
    at x_ite.min.js:6
    at t (x_ite.min.js:6)
    at Map.forEach (<anonymous>)
    at i.processInterests (x_ite.min.js:6)
    at i.processEvent (x_ite.min.js:6)
    at C._set_live__ (x_ite.min.js:10)
    at x_ite.min.js:6
    at t (x_ite.min.js:6)
setError @ scripting.min.js:1

**Comment by olafgithub** [comment]
I just cleaned up the code of test.wrl a bit

- added one point to close the cross-section (I forgot to do so years ago) makes no difference.
- changed the angle of the extrusion to 0 - 300 degrees to make it a bit more interesting.
- added begin and endcaps to fully exercise all the JavaScript code.

No change: still not showing the shape with 4.7.1

Olaf

**Comment by create3000** [comment]
The bug is due to that I have implemented Symbol.iterator handling in MF* fields, which enables `for of` loops. 

Also I have removed in this version old code and replaced with new more concise code. Unfortunately some bug have crept in.

Your test files and scenes should work well now.

**Comment by olafgithub** [comment]
Thanks. 

Confirmed, 

Again very quick response!

Olaf
