### ISSUE TITLE
Different handling of Viewpoint change btw version 4.7.0 and 4.7.1

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#91]
Version 4.7.0

When I change Viewpoint (with the context menu or Page Up / Page Down / Home keys) there is a **nice smooth transition** between the previous and new viewpoint. As I am used to in other VRML Viewers.

Version 4.7.1

The change between Viewpoints is immediately (without the smooth transition)

Note: I left the **jump field** at **_default_** (that is **TRUE**).

On Windows 10
Google Chrome: Version 96.0.4664.110 (Official Build) (64-bit)

Olaf

**Comment by olafgithub** [comment]
Check it out

https://satadorus.eu/x_ite/yacs_2_0/yacs_2_0.html                         (**version 4.7.0**) 
https://satadorus.eu/x_ite/cbx_engine_2_0/cbx_engine_2_0.html   (**latest = version 4.7.1**)

**Comment by olafgithub** [comment]
**Ignore the closed 
My mistake**

To see the issue:

https://satadorus.eu/x_ite/yacs_2_0/yacs_2_0.html **(version 4.7.0)**
https://satadorus.eu/x_ite/cbx_engine_2_0/cbx_engine_2_0.html **(latest = version 4.7.1)**

Olaf

**Comment by create3000** [comment]
Works again.

**Comment by olafgithub** [comment]
Great
Confirmed
Thanks

Olaf
