### ISSUE TITLE
X_ITE breaks when Ruffle extension is installed

### ISSUE THREAD

**Issue by Sgeo** [create3000/x_ite#92]
**Describe the bug**
X_ITE fails to load worlds when Ruffle is installed

**To Reproduce**
1. Install Ruffle from https://chrome.google.com/webstore/detail/ruffle/donbcfbmhbcapadipfkeojnmajbakjdc
2. Visit a site that uses X_ITE such as https://sgeo.github.io/floopsArchive/floops/floops7.html

**Expected behavior**
X_ITE should load normally.

**Additional context**
Per @n0samu, this appears to be caused by X_ITE's getScriptURL code getting confused when another script tag is added to the page.

It may make sense to store the value of `document.currentScript.src` when X_ITE loads, and return that value from getScriptURL, instead of assuming that the last script tag on the page will always be X_ITE.

**Comment by create3000** [comment]
Thank you, `document.currentScript.src` was not available when started programming X_ITE. Works great.

**Comment by create3000** [comment]
LOL Flops.

**Comment by create3000** [comment]
Fix released. You should use 'latest' version now.
