### ISSUE TITLE
Shaders don't work on localhost express server.   Non-express remote works okay.  Makes debugging difficult

### ISSUE THREAD

**Issue by coderextreme** [create3000/x_ite#93]
**Describe the bug**
Shader not applied properly on localhost.

**To Reproduce**
Shading fails here:  https://localhost:3000/src/main/html/x_iteflowers.xhtml
Buts succeeds here: https://coderextreme.net/X3DJSONLD/src/main/html/x_iteflowers.xhtml

**Expected behavior**
Shading applied on both sites

**Screenshots**
![image](https://user-images.githubusercontent.com/705783/150020811-3aa16098-ae84-4740-b8bd-6492bc8fcf7d.png)

![image](https://user-images.githubusercontent.com/705783/150020861-ce3c6552-dcdd-4267-8fec-5e697c1ae484.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  WIndows 10
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] Version 97.0.1072.62 (Official build) (64-bit)

**Additional context**

Running ```node app.js``` in X3DJSONLD.  Recommend running ```npm install``` after removing postinstall from package.json file.

Network shows all URLs returned with status 200

One error in log stood out. This error also appeared on coderextreme.net page.

**Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.**

Web console log for localhost (can't copy whole thing)

Welcome to X_ITE X3D Browser 4.7.3:
   Current Graphics Renderer
      Name: Google Inc. (NVIDIA) ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729)
      WebGL version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
      Shading language: WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
   Rendering Properties
      Antialiased: true
      Depth size: 24 bits
      Color depth: 32 bits
      Max clip planes: 6
      Max global lights: 4
      Max textures: 2
      Texture units: 32
      Max texture size: 16384 × 16384 pixel
      Texture memory: NaN
      Max vertex uniform vectors: 4095
      Max fragment uniform vectors: 1024
      Max vertex attribs: 16

Welcome to X_ITE X3D Browser 4.7.3:
   Current Graphics Renderer
      Name: Google Inc. (NVIDIA) ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9729)
      WebGL version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
      Shading language: WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
   Rendering Properties
      Antialiased: true
      Depth size: 24 bits
      Color depth: 32 bits
      Max clip planes: 6
      Max global lights: 4
      Max textures: 2
      Texture units: 32
      Max texture size: 16384 × 16384 pixel
      Texture memory: NaN
      Max vertex uniform vectors: 4095
      Max fragment uniform vectors: 1024
      Max vertex attribs: 16

x_ite_dom.1.3.js:17 X_ITE XHTML DOM integration enabled
x_ite.min.js:24 
        
       Couldn't load URL 'https://localhost:3000/src/main/shaders/x_ite_flowers_chromatic.vs': ShaderPart '': ERROR: 0:1: 'version' : #version directive must occur before anything else, except for comments and white space
ERROR: 0:6: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:7: 'in' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:20: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:21: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:22: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:23: 'out' : storage qualifier supported in GLSL ES 3.00 and above only
ERROR: 0:24: 'out' : storage qualifier supported in GLSL ES 3.00 and above only

**Comment by create3000** [comment]
If you load https://localhost:3000/src/main/shaders/x_ite_flowers_chromatic.vs, are there some random chars (whitespaces or so) before your `#version` directive?

**Comment by coderextreme** [comment]
Maybe there are caching issues?  I don’t know if express does caching or
not.  This should be identical file:

https://coderextreme.net/X3DJSONLD/src/main/shaders/x_ite_flowers_chromatic.vs

Also a similar file can be checked on GitHub under coderextreme user,
X3DJSONLD repository.

I did edit the files a couple of times today, removing #ifdef and promoting
precision of float.

I’m a little unsure about networking since our router/modem is on the
blink, and I’ve notice loading delays from the network.   But I would think
localhost would be okay.   Would CORS possibly apply???

I’ll revisit this when I get back to my localhost to look at the browser
network tab and response text.  I have noticed XML parsing of shader
files.  Perhaps one can specify the content type one desires?   I have a
great express function for assigning content type to file extensions.  See
app.js under coderextreme’s X3DJSONLD GitHub repository (search for .vs and
.fs or shader.  I am not sure if content type has changed for shaders.
That’s one thing to check.

John

**Comment by coderextreme** [comment]
This page indicates text/plain content type is correct for shaders, which
is what I have.  I have seen reference to text/plain being in the spec, but
I haven’t looked at the Khronos spec.

https://stackoverflow.com/questions/28946976/mime-type-for-shader-code

Here is the express app.js:

https://github.com/coderextreme/X3DJSONLD/blob/master/app.js

Here is the shader file:


https://github.com/coderextreme/X3DJSONLD/blob/master/src/main/shaders/x_ite_flowers_chromatic.vs


When I get to localhost, I will check server logs and request/reply in web
dev tools.


Thanks for your assistance.

John

**Comment by create3000** [comment]
Have you tried an different localhost server software program? There is nothing special between localhost and a web address from the view of X_ITE. But the server app differs, app.js vs apache (mostly). That's why I think the localhost server app does not server proper files. I have tried express server on my machine and I works properly with your example but I do not have a https localhost. Maybe it is the https?

**Comment by coderextreme** [comment]
Here's Edge snapshot.  See selected vertex shader and response.  I'm not seeing problems yet, Except for the rendering.

![image](https://user-images.githubusercontent.com/705783/150050674-6f1ee317-0373-4d41-9d72-d920a7280ac4.png)

**Comment by coderextreme** [comment]
Does GLSL ES 3.0 contain "uniform"? Good thing to look up?

**Comment by coderextreme** [comment]
Check out this screenshot (X_ITE shaders are encrypted/compressed?).   Do I
also need handling of my shaders serverside so they are
encrypted/compressed?   I will look at Networking on my remote site.

[image: image.png]
