### ISSUE TITLE
Bug or feature in Viewpoint handling

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#95]
To create a movie using video capture I created a series of Viewpoints.
The idea was to use PageUp and PageDown to change Viewpoint.
The transitions are very smooth!

Problem: the viewpoint Description is displayed in the upper right corner after the triangle.
I just removed the Description field from the Viewpoint, but then they could no longer be selected with PgUp and PgDown.
I then changed the Description string to "" (empty string). That did not work.
If a change all the Viewpoint Description strings to " " (a single space) it works, but I still see the little triangle.
When I Right-Click for the menu and select Viewpoints, I see the empty Viewpoints in the Viewpoint menu.

I noticed that in BS Contact it is possible to remove the Description fields and still use PageUp and PageDown.
But the movement between Viewpoints is more erratic. Not as smooth as with X_ITE.

Is there an easy way to get rid of the triangle and text and still use PageUp and PageDown to move between Viewpoints?

I know I could use a keyboard handler and bind the Viewpoints with JavaScript as I did before.
Just wondering...

**Windows 10
Google Chrome
X_ITE version v4.7.6**

Thanks.

Olaf
satadorus.eu

**Comment by create3000** [comment]
There is an `notifications` attribute of the X3DCanvas elements that can be toggled. See also https://create3000.github.io/x_ite/#notifications.

**Comment by olafgithub** [comment]
Thanks!

I noticed that the documentation on GitHub is much improved!
Works fine now. And I can still use the context menu to manually select a Viewpoint. In my project I use Browser.changeViewpoint( '...' ) to select the required viewpoint under program control. 

Olaf
