### ISSUE TITLE
Viewpoint NOT COPIED with Shift-F8 when in full screen mode

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#96]
I needed to insert a few Viewpoints in a VRML file.
I did the usual thing: used Shift-F8 to copy the current Viewpoint to the clipboard.
Returned to the Editor (VRMLPAD) and used Ctr-V to copy the Viewpoint in the file.

This works fine when I use Shift-F8 in windowed mode.
When I set the X_ITE browser to Fullscreen mode it does not work.

I noticed that in fullscreen mode I see the text "_Copied viewpoint to clipboard._" in the upper right corner.
When I return to the editor and use Ctrl-V to paste it, a text I copied to the clipboard much earlier was pasted.

**Windows 10
Google Chome
X_ITE: v4.7.6**

Olaf
satadorus.eu

**Comment by create3000** [comment]
In the meanwhile until to the next release, you can manually copy the viewpoint from the developer console of your browser.

**Comment by olafgithub** [comment]
Thanks,
In the meantime, I just used a 70% version of the FHD screen to get the Viewpoints.
I realized that it was a very minor bug from my perspective. But it could have other implications for the software.

Olaf

**Comment by olafgithub** [comment]
I noticed some strange behavior:
When ( in windowed mode) I use Shift-F8 a viewpoint is written to the debug console.
When I then change the viewpoint, zoom, and move (all in Examine mode) and use Shift-F8 again, often THE SAME Viewpoint is written on the console.
The same thing happens in Full-Screen mode.
At other times it looks like it works.
This needs some more looking into I am afraid.

Olaf

**Comment by create3000** [comment]
Have now tested with latest changes applied on Windows Chrome and other browsers and it seems to work. Have released an alpha version:

```html
<link rel="stylesheet" type="text/css" href="https://create3000.github.io/code/x_ite/alpha/dist/x_ite.css"/>
<script type="text/javascript" src="https://create3000.github.io/code/x_ite/alpha/dist/x_ite.min.js"></script>
```

Maybe you could test this, an hopefully confirm that it is working now.

**Comment by olafgithub** [comment]
Hi Holger,

I did a few quick tests...
Looks OK now! 
I get a different Viewpoint every time. Works in windowed and full-screen mode.

I see the same information on the clipboard and in the debug console.
Did previous versions also write the Viewpoint to the debug console?

This is a VERY NICE FEATURE. It makes it a lot easier to create a series of Viewpoints. Please leave it in!

Thanks,

Olaf

**Comment by create3000** [comment]
Sure I will leave it in! With the new version there is also support for clipboard OrthoViewpoint and GeoViewpoint, :). Should write documentation for keyboard shortcuts now.
