### ISSUE TITLE
Feature Request: Headlight control from context menu

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#97]
I noticed that it is not possible to turn the Headlight On or Off from the user interface (the context menu)
This can be nice if you add additional light to a scene.
This is how it is done in BS Contact:

![head_licht](https://user-images.githubusercontent.com/6066508/152391585-4469f35f-274f-477d-b648-f277796e9a2f.jpg)

Olaf

**Comment by create3000** [comment]
As NavigationInfo node has a headlight field, which can be set by the author, I think a menu item should not be needed. Why should it be useful?

**Comment by olafgithub** [comment]
I am aware of the headlight field in the NavigationInfo node.
What I like is to be able to switch the headlight on or off **while exploring a scene** to:
- Change the atmosphere (see the scene of diving in NEMO 33 Brussel)
- Show the luminous paint on a watch dial.

See the following images.

Thanks,

Olaf
![on_2](https://user-images.githubusercontent.com/6066508/152656110-e3a675c2-8a05-4043-91e1-234d09952bd8.jpg)
![off_2](https://user-images.githubusercontent.com/6066508/152656114-fdfd259a-2aa2-408d-973b-b701fe60b5cf.jpg)
![on_1](https://user-images.githubusercontent.com/6066508/152656120-46e52c94-8ed4-4250-b2cd-cea02f091a47.jpg)
![off_1](https://user-images.githubusercontent.com/6066508/152656127-4b8c8c2a-c50b-457f-8d66-b4b9d371f036.jpg)

**Comment by olafgithub** [comment]
I forgot to mention that I just started using the Headlight On/Off feature in other browsers because it was there.
For one VRML word I added a Billboard node with a dive timer, a depth gauge, and a headlight control:
Clicking the headlight toggles between On and Off via the Navigationinfo node.

![headlight_on](https://user-images.githubusercontent.com/6066508/152684958-dc82fb36-bb61-4456-8c07-3b1952432bdd.jpg)
![headlight_off](https://user-images.githubusercontent.com/6066508/152684963-b6f423eb-dac4-40aa-8966-a09f0f57c1c3.jpg)
