### ISSUE TITLE
Feature request: Make it possible to add items to the context menu to control the scene

### ISSUE THREAD

**Issue by olafgithub** [create3000/x_ite#98]
It would be nice if you could control the scene from the context menu.
This is how I used it in BS Contact:
Everything under the double horizontal line is added by me to control the scene,

![bs_contac_menu](https://user-images.githubusercontent.com/6066508/152392998-49062221-ec75-4b69-bbb2-fd0f49a9b704.jpg)

Olaf

**Comment by create3000** [comment]
This is now possible. Version 4.7.11 is now online. Short documentation at https://create3000.github.io/x_ite/#extending-the-context-menu.

**Comment by olafgithub** [comment]
Great!

Busy now. Will try it out later.

Olaf.

**Comment by olafgithub** [comment]
I tried it yesterday and today. Looks like you can now do almost everything from the context menu.

A few remarks:

**Documentation**
Maybe you can later add a complete example with more of the options like sub-menus, radio, buttons etc.
I got it to work, but without fully understanding how.

**Separators**
I tried to include some separators. Whatever I tried, no visible separator.
Only when I gave up and moved the viewer to a different display did I see the very faint separators.
I use LG E2541 displays. The main one is calibrated using a Spyder 5 Elite.
I then took a screenshot and found that the background of the context menu is **hex 222222** and the separator is **hex 111111**
Only then did I notice that you also have separators in the main context menu...

**Background Extend context menu**
Maybe it is possible to show the extended part of the context menu with a (slightly) different background color to make it stand out better.

**I feel it is a very nice and complete solution.**

Thanks,

Olaf
